export const preguntas = {
    "2030101000e": {
      preguntas: [
        {
          id: "2030101001",
          pregunta: "¿Qué es un Tipo Abstracto de Datos (TAD)?",
          opciones: [
            "Solo una Estructura de Datos",
            "Solo un conjunto de operaciones",
            "La suma de una Estructura de Datos y las operaciones que se pueden realizar sobre ella",
            "Un tipo de dato básico del sistema operativo",
          ],
          correcta: 2,
          preguntaId: "2030101001",
        },
        {
          id: "2030101002",
          pregunta: "¿Qué significa FIFO en el contexto de las estructuras de datos?",
          opciones: ["First In, First Out", "Fast Input, Fast Output", "File Input, File Output", "Final In, First Out"],
          correcta: 0,
          preguntaId: "2030101002",
        },
        {
          id: "2030101003",
          pregunta: "En un árbol, ¿qué es un nodo terminal o hoja?",
          opciones: [
            "El nodo raíz",
            "Un nodo que tiene el máximo número de hijos",
            "Un nodo que no tiene subárboles",
            "El nodo con el nivel más alto",
          ],
          correcta: 2,
          preguntaId: "2030101003",
        },
        {
          id: "2030101004",
          pregunta: "¿Cuál es la diferencia principal entre el recorrido en profundidad y en anchura de un árbol?",
          opciones: [
            "El recorrido en profundidad visita primero todos los hijos de un nodo antes de pasar al siguiente nodo",
            "El recorrido en anchura visita primero el hijo más profundo de cada nodo",
            "El recorrido en profundidad visita primero el primer hijo de cada nodo, mientras que el recorrido en anchura visita todos los nodos de un nivel antes de pasar al siguiente",
            "No hay diferencia, son términos intercambiables",
          ],
          correcta: 2,
          preguntaId: "2030101004",
        },
        {
          id: "2030101005",
          pregunta: "En un recorrido en preorden de un árbol binario, ¿cuál es el orden correcto de visita?",
          opciones: [
            "Izquierda, raíz, derecha",
            "Raíz, izquierda, derecha",
            "Derecha, raíz, izquierda",
            "Izquierda, derecha, raíz",
          ],
          correcta: 1,
          preguntaId: "2030101005",
        },
        {
          id: "2030101006",
          pregunta: "¿Qué característica define a un Árbol Binario de Búsqueda?",
          opciones: [
            "Todos los nodos tienen exactamente dos hijos",
            "La altura del árbol siempre es logarítmica",
            "Los valores en el subárbol izquierdo son menores que los del subárbol derecho",
            "Todos los nodos hoja están en el mismo nivel",
          ],
          correcta: 2,
          preguntaId: "2030101006",
        },
        {
          id: "2030101007",
          pregunta: "¿Cuál es la principal diferencia entre estructuras de datos estáticas y dinámicas?",
          opciones: [
            "Las estructuras estáticas son más rápidas que las dinámicas",
            "Las estructuras dinámicas pueden cambiar de tamaño en tiempo de ejecución",
            "Las estructuras estáticas solo pueden contener tipos de datos simples",
            "Las estructuras dinámicas no requieren punteros",
          ],
          correcta: 1,
          preguntaId: "2030101007",
        },
        {
          id: "2030101008",
          pregunta: "¿Qué es un registro en el contexto de estructuras de datos?",
          opciones: [
            "Un tipo de dato básico del sistema operativo",
            "Un conjunto de datos vistos como una entidad completa",
            "Una estructura de datos que solo puede contener un tipo de dato",
            "Un tipo de árbol binario",
          ],
          correcta: 1,
          preguntaId: "2030101008",
        },
        {
          id: "2030101002",
          pregunta: "¿Qué significa LIFO en el contexto de las estructuras de datos?",
          opciones: ["Last In, First Out", "Long Input, Fast Output", "List Input, File Output", "Large In, Few Out"],
          correcta: 0,
          preguntaId: "2030101009",
        },
        
      ],
      minimoParaAprobar: 7,
    },
      "2030102000e": {
    preguntas: [
      {
        id: "2030102001",
        pregunta: "¿Qué es la organización de ficheros?",
        opciones: [
          "Una función de las aplicaciones de usuario",
          "Una funcionalidad reservada a los sistemas operativos",
          "Un tipo de estructura de datos",
          "Un método de compresión de archivos",
        ],
        correcta: 1,
        preguntaId: "2030102001",
      },
      {
        id: "2030102002",
        pregunta: "¿Cuál es la principal característica de la organización secuencial?",
        opciones: [
          "Utiliza punteros para enlazar registros",
          "El orden físico coincide con el orden lógico",
          "Utiliza una función hash para ubicar registros",
          "Divide los ficheros en tres partes",
        ],
        correcta: 1,
        preguntaId: "2030102002",
      },
      {
        id: "2030102003",
        pregunta: "En la organización secuencial encadenada, ¿qué permite el borrado selectivo?",
        opciones: [
          "La función hash",
          "La fragmentación interna",
          "La redirección de punteros",
          "El fichero de overflow",
        ],
        correcta: 2,
        preguntaId: "2030102003",
      },
      {
        id: "2030102004",
        pregunta: "¿Cuántos ficheros físicos componen la organización secuencial indexada?",
        opciones: ["Uno", "Dos", "Tres", "Cuatro"],
        correcta: 2,
        preguntaId: "2030102004",
      },
      {
        id: "2030102005",
        pregunta:
          "¿Cuál es la principal ventaja de la organización secuencial indexada encadenada sobre la secuencial indexada?",
        opciones: [
          "Elimina la necesidad de un fichero de overflow",
          "Permite un acceso más directo a los registros, reduciendo el tiempo de búsqueda",
          "No requiere mantener una estructura de punteros",
          "Elimina por completo la fragmentación",
        ],
        correcta: 1,
        preguntaId: "2030102005",
      },
      {
        id: "2030102006",
        pregunta: "En la organización directa, relativa o aleatoria, ¿cómo se obtiene la posición física del registro?",
        opciones: [
          "Mediante un índice secuencial",
          "A través de una función hash",
          "Por el orden de inserción",
          "Utilizando punteros encadenados",
        ],
        correcta: 1,
        preguntaId: "2030102006",
      },
      {
        id: "2030102007",
        pregunta: "¿Qué es la fragmentación interna?",
        opciones: [
          "El espacio sin usar dentro de un bloque de memoria asignado",
          "La separación física de los bloques de un mismo archivo",
          "La división de un archivo en múltiples partes",
          "El proceso de reorganización de archivos en el disco",
        ],
        correcta: 0,
        preguntaId: "2030102007",
      },
      {
        id: "2030102007",
        pregunta: "¿Cómo se soluciona la fragmentación externa?",
        opciones: [
          "Creando bloques de memoria más pequeños",
          "Utilizando una organización secuencial",
          "Realizando un proceso de defragmentación",
          "Implementando una función hash más eficiente",
        ],
        correcta: 2,
        preguntaId: "2030102008",
      },
      {
        id: "2030102005",
        pregunta: "En la organización secuencial indexada, ¿cuál es la función del fichero de overflow?",
        opciones: [
          "Contener los índices de los registros",
          "Almacenar los registros principales",
          "Guardar temporalmente los nuevos registros añadidos",
          "Mantener la estructura de punteros",
        ],
        correcta: 2,
        preguntaId: "2030102010",
      },
    ],
    minimoParaAprobar: 7,
  },
  "2030103000e": {
    preguntas: [
      {
        id: "2030103001",
        pregunta: "¿Cuál de las siguientes NO es una característica clave de los algoritmos?",
        opciones: ["Son ordenados", "Son finitos", "Son deterministas", "Son infinitos"],
        correcta: 3,
        preguntaId: "2030103001",
      },
      {
        id: "2030103002",
        pregunta: "¿Cuál es la principal diferencia entre una función y un procedimiento?",
        opciones: [
          "Las funciones no pueden recibir parámetros",
          "Los procedimientos siempre devuelven múltiples resultados",
          "Las funciones devuelven un único resultado, mientras que los procedimientos pueden devolver varios, uno o ninguno",
          "Los procedimientos solo pueden usar variables globales",
        ],
        correcta: 2,
        preguntaId: "2030103002",
      },
      {
        id: "2030103003",
        pregunta: "¿Qué se busca idealmente en términos de cohesión y acoplamiento en el diseño de software?",
        opciones: [
          "Alta cohesión y alto acoplamiento",
          "Baja cohesión y bajo acoplamiento",
          "Alta cohesión y bajo acoplamiento",
          "Baja cohesión y alto acoplamiento",
        ],
        correcta: 2,
        preguntaId: "2030103003",
      },
      {
        id: "2030103004",
        pregunta: "¿Cuál de los siguientes tipos de acoplamiento es considerado el más débil?",
        opciones: [
          "Acoplamiento de contenido",
          "Acoplamiento común",
          "Acoplamiento de control",
          "Acoplamiento de datos",
        ],
        correcta: 3,
        preguntaId: "2030103004",
      },
      {
        id: "2030103005",
        pregunta: "¿Cuál es el tipo de cohesión más fuerte?",
        opciones: ["Cohesión casual", "Cohesión lógica", "Cohesión temporal", "Cohesión funcional"],
        correcta: 3,
        preguntaId: "2030103005",
      },
      {
        id: "2030103006",
        pregunta: "¿Qué ocurre con una variable pasada por referencia a un subprograma?",
        opciones: [
          "Se crea una copia local de la variable en el subprograma",
          "La variable original no puede ser modificada por el subprograma",
          "Las modificaciones en el subprograma afectan al valor original en el programa principal",
          "La variable se convierte automáticamente en una variable global",
        ],
        correcta: 2,
        preguntaId: "2030103006",
      },
      {
        id: "2030103007",
        pregunta: "¿Cuál es una característica esencial de un algoritmo recursivo?",
        opciones: [
          "Siempre es más eficiente que un algoritmo iterativo",
          "No necesita una condición de parada",
          "Se llama a sí mismo para resolver un problema",
          "Solo puede ser implementado en lenguajes de programación orientados a objetos",
        ],
        correcta: 2,
        preguntaId: "2030103007",
      },
      {
        id: "2030103008",
        pregunta: "¿Qué es el backtracking?",
        opciones: [
          "Un tipo de bucle en programación",
          "Un algoritmo de ordenación",
          "Un método para optimizar funciones recursivas",
          "Un algoritmo de vuelta atrás que enumera sistemáticamente todas las alternativas posibles",
        ],
        correcta: 3,
        preguntaId: "2030103008",
      },
      {
        id: "2030103009",
        pregunta: "¿Cuál de los siguientes algoritmos de búsqueda requiere que el array esté ordenado?",
        opciones: [
          "Búsqueda secuencial sin centinela",
          "Búsqueda secuencial con centinela",
          "Búsqueda binaria",
          "Ninguna de las anteriores",
        ],
        correcta: 2,
        preguntaId: "2030103009",
      },
      {
        id: "2030103010",
        pregunta: "¿Qué algoritmo de ordenación divide la lista en dos partes usando un pivote?",
        opciones: ["Método de la burbuja", "Método de selección", "Método de inserción", "Quicksort"],
        correcta: 3,
        preguntaId: "2030103010",
      },
    ],
    minimoParaAprobar: 8,
  },
  "2030104000e": {
    preguntas: [
      {
        id: "2030104001",
        pregunta: "¿Por qué es necesario almacenar los datos de la Memoria Principal en un medio persistente?",
        opciones: [
          "Para aumentar la velocidad de procesamiento",
          "Para estar disponibles en el futuro o liberar memoria para otros procesos",
          "Para encriptar la información",
          "Para cumplir con las normas de la Administración General del Estado",
        ],
        correcta: 1,
        preguntaId: "2030104001",
      },
      {
        id: "2030104002",
        pregunta: "¿Cuáles son las dos formas principales de clasificar los ficheros según el texto?",
        opciones: [
          "Por tamaño y por fecha de creación",
          "Por contenido y por forma de almacenamiento",
          "Por extensión y por programa que los crea",
          "Por ubicación en el disco y por permisos",
        ],
        correcta: 1,
        preguntaId: "2030104002",
      },
      {
        id: "2030104003",
        pregunta: "¿Qué es una extensión de archivo?",
        opciones: [
          "Un tipo de compresión de datos",
          "Una forma de identificar fácilmente el tipo de archivo",
          "Un método para aumentar el tamaño de un archivo",
          "Un protocolo de transferencia de archivos",
        ],
        correcta: 1,
        preguntaId: "2030104003",
      },
      {
        id: "2030104004",
        pregunta: "¿Qué formato se utiliza comúnmente para archivos de texto plano?",
        opciones: [".docx", ".txt", ".pdf", ".jpg"],
        correcta: 1,
        preguntaId: "2030104004",
      },
      {
        id: "2030104005",
        pregunta:
          "¿Cuál de los siguientes es un formato de archivo de imagen admitido por las Administraciones según la lista proporcionada?",
        opciones: ["DOC", "EXE", "PNG", "WAV"],
        correcta: 2,
        preguntaId: "2030104005",
      },
      {
        id: "2030104005",
        pregunta: "¿Qué significa la extensión CSV?",
        opciones: [
          "Compact Stored Values",
          "Computer System Verification",
          "Comma Separated Values",
          "Centralized Storage Version",
        ],
        correcta: 2,
        preguntaId: "2030104006",
      },
      {
        id: "2030104005",
        pregunta: "¿Cuál de los siguientes formatos es comúnmente utilizado para documentos portátiles?",
        opciones: ["TXT", "JPG", "PDF", "MP3"],
        correcta: 2,
        preguntaId: "2030104007",
      },
      {
        id: "2030104005",
        pregunta: "¿Qué tipo de archivo se utiliza típicamente para hojas de estilo en desarrollo web?",
        opciones: ["HTML", "JS", "CSS", "PHP"],
        correcta: 2,
        preguntaId: "2030104008",
      },
      {
        id: "2030104005",
        pregunta: "¿Cuál de los siguientes es un formato de compresión de archivos mencionado en la lista?",
        opciones: ["RAR", "7Z", "ZIP", "TAR"],
        correcta: 2,
        preguntaId: "2030104009",
      },
      {
        id: "2030104005",
        pregunta: "¿Qué formato se utiliza comúnmente para archivos de audio comprimido?",
        opciones: ["WAV", "MP3", "FLAC", "MIDI"],
        correcta: 1,
        preguntaId: "2030104010",
      },
    ],
    minimoParaAprobar: 8,
  },
  }
  
  