export const preguntas = {
    "2020101000e": {
      preguntas: [
        {
          id: "2020101001",
          pregunta: "¿Cuál es la función principal de los periféricos en un sistema informático?",
          opciones: [
            "Procesar datos internamente",
            "Permitir la interacción entre el sistema y el exterior",
            "Almacenar información permanentemente",
            "Generar energía para el funcionamiento del sistema",
          ],
          correcta: 1,
          preguntaId: "2020101001",
        },
        {
          id: "2020101002",
          pregunta: "¿Qué tipo de periférico se utiliza tanto para introducir como para extraer información del sistema?",
          opciones: [
            "Periférico de entrada",
            "Periférico de salida",
            "Periférico mixto o de entrada/salida",
            "Periférico de procesamiento",
          ],
          correcta: 2,
          preguntaId: "2020101002",
        },
        {
          id: "2020101004",
          pregunta:
            "¿Qué distribución de teclado está diseñada específicamente para maximizar la ergonomía y eficiencia?",
          opciones: ["QWERTY", "AZERTY", "QUERTZ", "Dvorak"],
          correcta: 3,
          preguntaId: "2020101004",
        },
        {
          id: "2020101005",
          pregunta: "¿Qué tipo de interruptor de teclado es más propenso a sufrir problemas de 'ghosting'?",
          opciones: ["Interruptor mecánico", "Interruptor de membrana", "Interruptor óptico", "Interruptor capacitivo"],
          correcta: 1,
          preguntaId: "2020101005",
        },
        {
          id: "2020101006",
          pregunta: "¿Cuál de las siguientes NO es una tecnología común en ratones modernos?",
          opciones: ["Mecánica (con bola)", "Óptica", "Láser", "Capacitiva"],
          correcta: 3,
          preguntaId: "2020101006",
        },
        {
          id: "2020101007",
          pregunta: "¿Qué ventaja ofrece un trackball sobre un ratón convencional?",
          opciones: ["Mayor precisión", "Menor costo", "Requiere menos espacio de escritorio", "Mejor para juegos"],
          correcta: 2,
          preguntaId: "2020101007",
        },
        {
          id: "2020101008",
          pregunta: "¿Qué tipo de pantalla táctil puede funcionar con cualquier objeto, incluso no conductor?",
          opciones: ["Capacitiva", "Resistiva", "Infrarroja", "OLED"],
          correcta: 1,
          preguntaId: "2020101008",
        },
        {
          id: "2020101010",
          pregunta: "¿Para qué se utiliza principalmente una tableta digitalizadora?",
          opciones: [
            "Procesamiento de texto",
            "Diseño gráfico y dibujo digital",
            "Reproducción de audio",
            "Almacenamiento de datos",
          ],
          correcta: 1,
          preguntaId: "2020101010",
        },
        {
          id: "2020101011",
          pregunta: "¿Qué tipo de tarjeta puede leer un lector de SmartCard?",
          opciones: [
            "Solo tarjetas de crédito",
            "Únicamente tarjetas SD",
            "DNI electrónico",
            "Exclusivamente tarjetas SIM",
          ],
          correcta: 2,
          preguntaId: "2020101011",
        },
        {
          id: "2020101012",
          pregunta:
            "¿Qué tipo de micrófono utiliza la diferencia de carga eléctrica entre un diafragma y una placa para generar señal?",
          opciones: ["Micrófono dinámico", "Micrófono de cinta", "Micrófono de condensador", "Micrófono piezoeléctrico"],
          correcta: 2,
          preguntaId: "2020101012",
        },
        {
          id: "2020101013",
          pregunta: "¿Cuál de los siguientes NO es un dispositivo común para juegos?",
          opciones: ["Joystick", "Gamepad", "Kinect", "Escáner"],
          correcta: 3,
          preguntaId: "2020101013",
        },
        {
          id: "2020101015",
          pregunta: "¿Cuál es el dispositivo de salida más común en un sistema informático?",
          opciones: ["Impresora", "Altavoces", "Monitor", "Proyector"],
          correcta: 2,
          preguntaId: "2020101015",
        },
        {
          id: "2020101016",
          pregunta:
            "¿Qué componente fue crucial para mejorar la calidad de audio en los PC con la introducción del CD-ROM?",
          opciones: ["Altavoces estéreo", "Chips PCM", "Puertos MIDI", "Tarjetas Sound Blaster"],
          correcta: 1,
          preguntaId: "2020101016",
        },
        {
          id: "2020101016",
          pregunta: "En un sistema de audio 5.1, ¿cuántos canales de audio hay en total?",
          opciones: ["5", "6", "7", "8"],
          correcta: 1,
          preguntaId: "2020101016",
        },
        {
          id: "2020101017",
          pregunta: "¿Qué tipo de auriculares utilizan vibraciones en los huesos del cráneo para transmitir el sonido?",
          opciones: ["Circumaurales", "Supraurales", "Intraurales", "De conducción ósea"],
          correcta: 3,
          preguntaId: "2020101017",
        },
        {
          id: "2020101018",
          pregunta: "¿Qué dispositivo de salida es especialmente útil para personas con discapacidad visual?",
          opciones: [
            "Monitor de alto contraste",
            "Altavoces de alta fidelidad",
            "Lector de pantalla Braille",
            "Teclado retroiluminado",
          ],
          correcta: 2,
          preguntaId: "2020101018",
        },
      ],
      minimoParaAprobar: 12,
    },
    "2020102000e": {
    preguntas: [
      {
        id: "2020102001",
        pregunta: "¿Cuáles son los dos tipos principales de operaciones que realizan los periféricos?",
        opciones: [
          "Entrada y salida",
          "Sincronización y transferencia de datos",
          "Lectura y escritura",
          "Procesamiento y almacenamiento",
        ],
        correcta: 1,
        preguntaId: "2020102001",
      },
      {
        id: "2020102001",
        pregunta: "¿Qué método de sincronización libera a la CPU de consultar periódicamente el estado del periférico?",
        opciones: ["Polling o sondeo", "Interrupciones", "Sincronización por programa", "Transferencia de datos"],
        correcta: 1,
        preguntaId: "2020102002",
      },
      {
        id: "2020102002",
        pregunta: "En una conexión serie, ¿cómo se transmiten los datos?",
        opciones: ["Varios bits simultáneamente", "Bit a bit", "Byte a byte", "En paquetes completos"],
        correcta: 1,
        preguntaId: "2020102003",
      },
      {
        id: "2020102003",
        pregunta: "¿Qué tipo de conector se asocia comúnmente con el término 'puerto serie' en informática?",
        opciones: ["USB", "RS-232 (DE-9 o DB-9)", "Firewire", "HDMI"],
        correcta: 1,
        preguntaId: "2020102004",
      },
      {
        id: "2020102004",
        pregunta: "¿Qué ventaja ofrece la transmisión diferencial utilizada en USB?",
        opciones: [
          "Mayor velocidad de transmisión",
          "Menor consumo de energía",
          "Mayor robustez ante interferencias externas",
          "Compatibilidad con más dispositivos",
        ],
        correcta: 2,
        preguntaId: "2020102005",
      },
      {
        id: "2020102004",
        pregunta: "¿Qué permite la especificación USB OTG?",
        opciones: [
          "Aumentar la velocidad de transmisión",
          "Conectar dispositivos USB a la red eléctrica",
          "Que los dispositivos USB actúen como servidores",
          "Reducir el consumo de energía de los dispositivos USB",
        ],
        correcta: 2,
        preguntaId: "2020102006",
      },
      {
        id: "2020102005",
        pregunta: "¿Cuál es una ventaja de Firewire sobre USB?",
        opciones: [
          "Mayor velocidad de transmisión",
          "Menor consumo de energía",
          "Modo 'peer-to-peer' sin intervención de la CPU",
          "Mayor compatibilidad con dispositivos",
        ],
        correcta: 2,
        preguntaId: "2020102007",
      },
      {
        id: "2020102006",
        pregunta: "¿Qué característica comparten Thunderbolt y USB en cuanto a la conexión de dispositivos?",
        opciones: [
          "Ambos son estándares de Apple",
          "Permiten hot swap",
          "Utilizan el mismo tipo de conector",
          "Tienen la misma velocidad de transmisión",
        ],
        correcta: 1,
        preguntaId: "2020102008",
      },
      {
        id: "2020102007",
        pregunta: "Según la tabla comparativa, ¿qué estándar alcanza una velocidad de 5 GB/s?",
        opciones: ["USB 3.2", "Thunderbolt 2", "Thunderbolt 3", "USB 4.0"],
        correcta: 2,
        preguntaId: "2020102009",
      },
      {
        id: "2020102008",
        pregunta: "¿Cuál de los siguientes NO es un puerto de salida gráfica mencionado en el texto?",
        opciones: ["VGA", "DVI", "HDMI", "USB-C"],
        correcta: 3,
        preguntaId: "2020102010",
      },
      {
        id: "2020102009",
        pregunta: "¿Para qué tipo de necesidades se reserva principalmente la transmisión paralela en la actualidad?",
        opciones: [
          "Dispositivos de bajo ancho de banda",
          "Conexiones inalámbricas",
          "Necesidades de muy alto ancho de banda",
          "Dispositivos de bajo costo",
        ],
        correcta: 2,
        preguntaId: "2020102011",
      },
      {
        id: "2020102010",
        pregunta: "¿Cuál es el formato más extendido del puerto Jack de audio?",
        opciones: ["2.5 mm", "3.5 mm", "6.3 mm", "XLR"],
        correcta: 1,
        preguntaId: "2020102012",
      },
      {
        id: "2020102011",
        pregunta: "¿Qué tecnología inalámbrica requiere visibilidad directa entre el dispositivo y el equipo?",
        opciones: ["Bluetooth", "Wifi", "Infrarrojos", "Zigbee"],
        correcta: 2,
        preguntaId: "2020102013",
      },
      {
        id: "2020102011",
        pregunta: "¿Qué versión de Bluetooth permite una velocidad de transmisión de hasta 2Mbps?",
        opciones: ["Bluetooth 3.0", "Bluetooth 4.0", "Bluetooth 4.2", "Bluetooth 5.0"],
        correcta: 3,
        preguntaId: "2020102014",
      },
      {
        id: "2020102012",
        pregunta: "Según la tabla comparativa, ¿qué tecnología inalámbrica tiene el consumo más bajo?",
        opciones: ["Bluetooth", "Wifi", "ZigBee", "Infrarrojos"],
        correcta: 2,
        preguntaId: "2020102015",
      },
    ],
    minimoParaAprobar: 11,
  },
  "2020103000e": {
    preguntas: [
      {
        id: "2020103001",
        pregunta: "¿Qué es un controlador o driver en el contexto de los periféricos?",
        opciones: [
          "Un dispositivo hardware que conecta el periférico al ordenador",
          "Un software específico del sistema operativo que permite la comunicación con el periférico",
          "Una interfaz física entre el periférico y la placa base",
          "Un protocolo de comunicación estándar para todos los periféricos",
        ],
        correcta: 1,
        preguntaId: "2020103001",
      },
      {
        id: "2020103001",
        pregunta: "¿Cómo puede estar disponible un driver para un periférico en un sistema operativo?",
        opciones: [
          "Solo mediante instalación manual",
          "Únicamente integrado en el sistema operativo",
          "Integrado en el sistema operativo o mediante instalación ad hoc",
          "Siempre debe ser descargado de internet",
        ],
        correcta: 2,
        preguntaId: "2020103002",
      },
      {
        id: "2020103003",
        pregunta: "En Linux, ¿dónde se representan todos los dispositivos?",
        opciones: ["En el directorio /bin", "En el directorio /dev", "En el directorio /etc", "En el directorio /usr"],
        correcta: 1,
        preguntaId: "2020103003",
      },
      {
        id: "2020103003",
        pregunta: "Si un sistema Linux no dispone del driver necesario para un dispositivo, ¿dónde se pueden añadir?",
        opciones: ["En el directorio /dev", "En el directorio /etc", "En el directorio /lib", "En el directorio /bin"],
        correcta: 2,
        preguntaId: "2020103004",
      },
      {
        id: "2020103004",
        pregunta: "¿Qué tipo de dispositivo en Linux transmite únicamente un byte a la vez?",
        opciones: [
          "Dispositivos orientados a bloque",
          "Dispositivos orientados a carácter",
          "Dispositivos orientados a socket",
          "Dispositivos orientados a buffer",
        ],
        correcta: 1,
        preguntaId: "2020103005",
      },
      {
        id: "2020103004",
        pregunta: "¿Cuál de los siguientes es un ejemplo de dispositivo orientado a bloque en Linux?",
        opciones: ["/dev/mouse", "/dev/tty1", "/dev/lp0", "/dev/hda"],
        correcta: 3,
        preguntaId: "2020103006",
      },
      {
        id: "2020103004",
        pregunta: "¿Qué tipo de dispositivos en Linux sirven para la comunicación entre procesos?",
        opciones: [
          "Dispositivos orientados a carácter",
          "Dispositivos orientados a bloque",
          "Dispositivos orientados a socket",
          "Dispositivos orientados a buffer",
        ],
        correcta: 2,
        preguntaId: "2020103007",
      },
      {
        id: "2020103005",
        pregunta: "En Windows, ¿a través de qué herramienta se administran los distintos periféricos?",
        opciones: [
          "Panel de control",
          "Administrador de tareas",
          "Administrador de dispositivos",
          "Configuración del sistema",
        ],
        correcta: 2,
        preguntaId: "2020103008",
      },
      {
        id: "2020103005",
        pregunta: "¿Cuáles son las extensiones de archivo comunes para los drivers en Windows?",
        opciones: [".exe, .dll, .bat", ".inf, .sys, .drv", ".doc, .xls, .ppt", ".zip, .rar, .7z"],
        correcta: 1,
        preguntaId: "2020103009",
      },
      {
        id: "2020103004",
        pregunta: "¿Cuál de los siguientes es un ejemplo de dispositivo orientado a socket en Linux?",
        opciones: ["/dev/mouse", "/dev/hda", "/dev/log", "/dev/tty1"],
        correcta: 2,
        preguntaId: "2020103010",
      },
    ],
    minimoParaAprobar: 7,
  },
  }
  
  