export const preguntas = {
    "2020101000e": {
      preguntas: [
        {
          id: "2020101001",
          pregunta: "¿Cuál es la función principal de los periféricos en un sistema informático?",
          opciones: [
            "Procesar datos internamente",
            "Permitir la interacción entre el sistema y el exterior",
            "Almacenar información permanentemente",
            "Generar energía para el funcionamiento del sistema",
          ],
          correcta: 1,
          preguntaId: "2020101001",
        },
        {
          id: "2020101002",
          pregunta: "¿Qué tipo de periférico se utiliza tanto para introducir como para extraer información del sistema?",
          opciones: [
            "Periférico de entrada",
            "Periférico de salida",
            "Periférico mixto o de entrada/salida",
            "Periférico de procesamiento",
          ],
          correcta: 2,
          preguntaId: "2020101002",
        },
        {
          id: "2020101004",
          pregunta:
            "¿Qué distribución de teclado está diseñada específicamente para maximizar la ergonomía y eficiencia?",
          opciones: ["QWERTY", "AZERTY", "QUERTZ", "Dvorak"],
          correcta: 3,
          preguntaId: "2020101004",
        },
        {
          id: "2020101005",
          pregunta: "¿Qué tipo de interruptor de teclado es más propenso a sufrir problemas de 'ghosting'?",
          opciones: ["Interruptor mecánico", "Interruptor de membrana", "Interruptor óptico", "Interruptor capacitivo"],
          correcta: 1,
          preguntaId: "2020101005",
        },
        {
          id: "2020101006",
          pregunta: "¿Cuál de las siguientes NO es una tecnología común en ratones modernos?",
          opciones: ["Mecánica (con bola)", "Óptica", "Láser", "Capacitiva"],
          correcta: 3,
          preguntaId: "2020101006",
        },
        {
          id: "2020101007",
          pregunta: "¿Qué ventaja ofrece un trackball sobre un ratón convencional?",
          opciones: ["Mayor precisión", "Menor costo", "Requiere menos espacio de escritorio", "Mejor para juegos"],
          correcta: 2,
          preguntaId: "2020101007",
        },
        {
          id: "2020101008",
          pregunta: "¿Qué tipo de pantalla táctil puede funcionar con cualquier objeto, incluso no conductor?",
          opciones: ["Capacitiva", "Resistiva", "Infrarroja", "OLED"],
          correcta: 1,
          preguntaId: "2020101008",
        },
        {
          id: "2020101010",
          pregunta: "¿Para qué se utiliza principalmente una tableta digitalizadora?",
          opciones: [
            "Procesamiento de texto",
            "Diseño gráfico y dibujo digital",
            "Reproducción de audio",
            "Almacenamiento de datos",
          ],
          correcta: 1,
          preguntaId: "2020101010",
        },
        {
          id: "2020101011",
          pregunta: "¿Qué tipo de tarjeta puede leer un lector de SmartCard?",
          opciones: [
            "Solo tarjetas de crédito",
            "Únicamente tarjetas SD",
            "DNI electrónico",
            "Exclusivamente tarjetas SIM",
          ],
          correcta: 2,
          preguntaId: "2020101011",
        },
        {
          id: "2020101012",
          pregunta:
            "¿Qué tipo de micrófono utiliza la diferencia de carga eléctrica entre un diafragma y una placa para generar señal?",
          opciones: ["Micrófono dinámico", "Micrófono de cinta", "Micrófono de condensador", "Micrófono piezoeléctrico"],
          correcta: 2,
          preguntaId: "2020101012",
        },
        {
          id: "2020101013",
          pregunta: "¿Cuál de los siguientes NO es un dispositivo común para juegos?",
          opciones: ["Joystick", "Gamepad", "Kinect", "Escáner"],
          correcta: 3,
          preguntaId: "2020101013",
        },
        {
          id: "2020101015",
          pregunta: "¿Cuál es el dispositivo de salida más común en un sistema informático?",
          opciones: ["Impresora", "Altavoces", "Monitor", "Proyector"],
          correcta: 2,
          preguntaId: "2020101015",
        },
        {
          id: "2020101016",
          pregunta:
            "¿Qué componente fue crucial para mejorar la calidad de audio en los PC con la introducción del CD-ROM?",
          opciones: ["Altavoces estéreo", "Chips PCM", "Puertos MIDI", "Tarjetas Sound Blaster"],
          correcta: 1,
          preguntaId: "2020101016",
        },
        {
          id: "2020101016",
          pregunta: "En un sistema de audio 5.1, ¿cuántos canales de audio hay en total?",
          opciones: ["5", "6", "7", "8"],
          correcta: 1,
          preguntaId: "2020101016",
        },
        {
          id: "2020101017",
          pregunta: "¿Qué tipo de auriculares utilizan vibraciones en los huesos del cráneo para transmitir el sonido?",
          opciones: ["Circumaurales", "Supraurales", "Intraurales", "De conducción ósea"],
          correcta: 3,
          preguntaId: "2020101017",
        },
        {
          id: "2020101018",
          pregunta: "¿Qué dispositivo de salida es especialmente útil para personas con discapacidad visual?",
          opciones: [
            "Monitor de alto contraste",
            "Altavoces de alta fidelidad",
            "Lector de pantalla Braille",
            "Teclado retroiluminado",
          ],
          correcta: 2,
          preguntaId: "2020101018",
        },
      ],
      minimoParaAprobar: 12,
    },
    "2020102000e": {
    preguntas: [
      {
        id: "2020102001",
        pregunta: "¿Cuáles son los dos tipos principales de operaciones que realizan los periféricos?",
        opciones: [
          "Entrada y salida",
          "Sincronización y transferencia de datos",
          "Lectura y escritura",
          "Procesamiento y almacenamiento",
        ],
        correcta: 1,
        preguntaId: "2020102001",
      },
      {
        id: "2020102001",
        pregunta: "¿Qué método de sincronización libera a la CPU de consultar periódicamente el estado del periférico?",
        opciones: ["Polling o sondeo", "Interrupciones", "Sincronización por programa", "Transferencia de datos"],
        correcta: 1,
        preguntaId: "2020102002",
      },
      {
        id: "2020102002",
        pregunta: "En una conexión serie, ¿cómo se transmiten los datos?",
        opciones: ["Varios bits simultáneamente", "Bit a bit", "Byte a byte", "En paquetes completos"],
        correcta: 1,
        preguntaId: "2020102003",
      },
      {
        id: "2020102003",
        pregunta: "¿Qué tipo de conector se asocia comúnmente con el término 'puerto serie' en informática?",
        opciones: ["USB", "RS-232 (DE-9 o DB-9)", "Firewire", "HDMI"],
        correcta: 1,
        preguntaId: "2020102004",
      },
      {
        id: "2020102004",
        pregunta: "¿Qué ventaja ofrece la transmisión diferencial utilizada en USB?",
        opciones: [
          "Mayor velocidad de transmisión",
          "Menor consumo de energía",
          "Mayor robustez ante interferencias externas",
          "Compatibilidad con más dispositivos",
        ],
        correcta: 2,
        preguntaId: "2020102005",
      },
      {
        id: "2020102004",
        pregunta: "¿Qué permite la especificación USB OTG?",
        opciones: [
          "Aumentar la velocidad de transmisión",
          "Conectar dispositivos USB a la red eléctrica",
          "Que los dispositivos USB actúen como servidores",
          "Reducir el consumo de energía de los dispositivos USB",
        ],
        correcta: 2,
        preguntaId: "2020102006",
      },
      {
        id: "2020102005",
        pregunta: "¿Cuál es una ventaja de Firewire sobre USB?",
        opciones: [
          "Mayor velocidad de transmisión",
          "Menor consumo de energía",
          "Modo 'peer-to-peer' sin intervención de la CPU",
          "Mayor compatibilidad con dispositivos",
        ],
        correcta: 2,
        preguntaId: "2020102007",
      },
      {
        id: "2020102006",
        pregunta: "¿Qué característica comparten Thunderbolt y USB en cuanto a la conexión de dispositivos?",
        opciones: [
          "Ambos son estándares de Apple",
          "Permiten hot swap",
          "Utilizan el mismo tipo de conector",
          "Tienen la misma velocidad de transmisión",
        ],
        correcta: 1,
        preguntaId: "2020102008",
      },
      {
        id: "2020102007",
        pregunta: "Según la tabla comparativa, ¿qué estándar alcanza una velocidad de 5 GB/s?",
        opciones: ["USB 3.2", "Thunderbolt 2", "Thunderbolt 3", "USB 4.0"],
        correcta: 2,
        preguntaId: "2020102009",
      },
      {
        id: "2020102008",
        pregunta: "¿Cuál de los siguientes NO es un puerto de salida gráfica mencionado en el texto?",
        opciones: ["VGA", "DVI", "HDMI", "USB-C"],
        correcta: 3,
        preguntaId: "2020102010",
      },
      {
        id: "2020102009",
        pregunta: "¿Para qué tipo de necesidades se reserva principalmente la transmisión paralela en la actualidad?",
        opciones: [
          "Dispositivos de bajo ancho de banda",
          "Conexiones inalámbricas",
          "Necesidades de muy alto ancho de banda",
          "Dispositivos de bajo costo",
        ],
        correcta: 2,
        preguntaId: "2020102011",
      },
      {
        id: "2020102010",
        pregunta: "¿Cuál es el formato más extendido del puerto Jack de audio?",
        opciones: ["2.5 mm", "3.5 mm", "6.3 mm", "XLR"],
        correcta: 1,
        preguntaId: "2020102012",
      },
      {
        id: "2020102011",
        pregunta: "¿Qué tecnología inalámbrica requiere visibilidad directa entre el dispositivo y el equipo?",
        opciones: ["Bluetooth", "Wifi", "Infrarrojos", "Zigbee"],
        correcta: 2,
        preguntaId: "2020102013",
      },
      {
        id: "2020102011",
        pregunta: "¿Qué versión de Bluetooth permite una velocidad de transmisión de hasta 2Mbps?",
        opciones: ["Bluetooth 3.0", "Bluetooth 4.0", "Bluetooth 4.2", "Bluetooth 5.0"],
        correcta: 3,
        preguntaId: "2020102014",
      },
      {
        id: "2020102012",
        pregunta: "Según la tabla comparativa, ¿qué tecnología inalámbrica tiene el consumo más bajo?",
        opciones: ["Bluetooth", "Wifi", "ZigBee", "Infrarrojos"],
        correcta: 2,
        preguntaId: "2020102015",
      },
    ],
    minimoParaAprobar: 11,
  },
  "2020103000e": {
    preguntas: [
      {
        id: "2020103001",
        pregunta: "¿Qué es un controlador o driver en el contexto de los periféricos?",
        opciones: [
          "Un dispositivo hardware que conecta el periférico al ordenador",
          "Un software específico del sistema operativo que permite la comunicación con el periférico",
          "Una interfaz física entre el periférico y la placa base",
          "Un protocolo de comunicación estándar para todos los periféricos",
        ],
        correcta: 1,
        preguntaId: "2020103001",
      },
      {
        id: "2020103001",
        pregunta: "¿Cómo puede estar disponible un driver para un periférico en un sistema operativo?",
        opciones: [
          "Solo mediante instalación manual",
          "Únicamente integrado en el sistema operativo",
          "Integrado en el sistema operativo o mediante instalación ad hoc",
          "Siempre debe ser descargado de internet",
        ],
        correcta: 2,
        preguntaId: "2020103002",
      },
      {
        id: "2020103003",
        pregunta: "En Linux, ¿dónde se representan todos los dispositivos?",
        opciones: ["En el directorio /bin", "En el directorio /dev", "En el directorio /etc", "En el directorio /usr"],
        correcta: 1,
        preguntaId: "2020103003",
      },
      {
        id: "2020103003",
        pregunta: "Si un sistema Linux no dispone del driver necesario para un dispositivo, ¿dónde se pueden añadir?",
        opciones: ["En el directorio /dev", "En el directorio /etc", "En el directorio /lib", "En el directorio /bin"],
        correcta: 2,
        preguntaId: "2020103004",
      },
      {
        id: "2020103004",
        pregunta: "¿Qué tipo de dispositivo en Linux transmite únicamente un byte a la vez?",
        opciones: [
          "Dispositivos orientados a bloque",
          "Dispositivos orientados a carácter",
          "Dispositivos orientados a socket",
          "Dispositivos orientados a buffer",
        ],
        correcta: 1,
        preguntaId: "2020103005",
      },
      {
        id: "2020103004",
        pregunta: "¿Cuál de los siguientes es un ejemplo de dispositivo orientado a bloque en Linux?",
        opciones: ["/dev/mouse", "/dev/tty1", "/dev/lp0", "/dev/hda"],
        correcta: 3,
        preguntaId: "2020103006",
      },
      {
        id: "2020103004",
        pregunta: "¿Qué tipo de dispositivos en Linux sirven para la comunicación entre procesos?",
        opciones: [
          "Dispositivos orientados a carácter",
          "Dispositivos orientados a bloque",
          "Dispositivos orientados a socket",
          "Dispositivos orientados a buffer",
        ],
        correcta: 2,
        preguntaId: "2020103007",
      },
      {
        id: "2020103005",
        pregunta: "En Windows, ¿a través de qué herramienta se administran los distintos periféricos?",
        opciones: [
          "Panel de control",
          "Administrador de tareas",
          "Administrador de dispositivos",
          "Configuración del sistema",
        ],
        correcta: 2,
        preguntaId: "2020103008",
      },
      {
        id: "2020103005",
        pregunta: "¿Cuáles son las extensiones de archivo comunes para los drivers en Windows?",
        opciones: [".exe, .dll, .bat", ".inf, .sys, .drv", ".doc, .xls, .ppt", ".zip, .rar, .7z"],
        correcta: 1,
        preguntaId: "2020103009",
      },
      {
        id: "2020103004",
        pregunta: "¿Cuál de los siguientes es un ejemplo de dispositivo orientado a socket en Linux?",
        opciones: ["/dev/mouse", "/dev/hda", "/dev/log", "/dev/tty1"],
        correcta: 2,
        preguntaId: "2020103010",
      },
    ],
    minimoParaAprobar: 7,
  },
    "2020201000e": {
      preguntas: [
        {
          id: "2020201001",
          pregunta: "¿Cuál es la principal función de las impresoras?",
          opciones: [
            "Escanear documentos",
            "Realizar la impresión en formato físico de los elementos diseñados en el ordenador",
            "Almacenar archivos digitales",
            "Procesar imágenes",
          ],
          correcta: 1,
          preguntaId: "2020201001",
        },
        {
          id: "2020201003",
          pregunta: "¿Cuál es una desventaja de las impresoras de inyección de tinta?",
          opciones: [
            "Son muy caras de adquirir",
            "No pueden imprimir en color",
            "La tinta tiende a secarse y bloquear los inyectores por falta de uso",
            "Son demasiado rápidas para uso doméstico",
          ],
          correcta: 2,
          preguntaId: "2020201002",
        },
        {
          id: "2020201004",
          pregunta: "¿Qué ventaja tienen las impresoras láser sobre las de inyección de tinta?",
          opciones: [
            "Son más baratas",
            "Usan cartuchos de tinta líquida",
            "Son más lentas pero de mayor calidad",
            "No sufren de los problemas de secado de material",
          ],
          correcta: 3,
          preguntaId: "2020201003",
        },
        {
          id: "2020201005",
          pregunta: "¿Por qué las impresoras de margarita y matriciales están actualmente en desuso?",
          opciones: [
            "Por su alto costo",
            "Por su lentitud y ruido",
            "Por su baja calidad de impresión",
            "Por su gran tamaño",
          ],
          correcta: 1,
          preguntaId: "2020201004",
        },
        {
          id: "2020201006",
          pregunta: "¿Qué tipo de impresora se usa principalmente en cajeros automáticos?",
          opciones: [
            "Impresora láser",
            "Impresora de inyección de tinta",
            "Impresora térmica",
            "Impresora de sublimación",
          ],
          correcta: 2,
          preguntaId: "2020201005",
        },
        {
          id: "2020201007",
          pregunta: "¿Cuál es el material más común en la impresión 3D?",
          opciones: ["Metal", "Cerámica", "Termoplástico", "Madera"],
          correcta: 2,
          preguntaId: "2020201006",
        },
        {
          id: "2020201007",
          pregunta: "¿Qué técnica se utiliza comúnmente en la impresión 3D con termoplásticos?",
          opciones: [
            "Estereolitografía",
            "Sinterizado selectivo por láser",
            "Modelado por deposición fundida (FDM)",
            "Impresión por inyección de aglutinante",
          ],
          correcta: 2,
          preguntaId: "2020201007",
        },
        {
          id: "2020201008",
          pregunta: "¿Cuál de los siguientes materiales de impresión 3D requiere una temperatura de cama más alta?",
          opciones: ["PLA", "ABS", "PETG", "HIPS"],
          correcta: 1,
          preguntaId: "2020201008",
        },
        {
          id: "2020201008",
          pregunta: "¿Qué característica es cierta para el PLA en comparación con el ABS?",
          opciones: [
            "Tiene mayor durabilidad",
            "Requiere una carcasa protectora durante la impresión",
            "Tiene emanaciones tóxicas",
            "No se deforma con altas temperaturas",
          ],
          correcta: 1,
          preguntaId: "2020201009",
        },
        {
          id: "2020201009",
          pregunta: "¿Para qué se utiliza comúnmente el filamento HIPS en la impresión 3D?",
          opciones: [
            "Como material principal para todas las impresiones",
            "Para crear objetos flexibles",
            "Para rellenar zonas huecas junto con el ABS",
            "Como alternativa ecológica al PLA",
          ],
          correcta: 2,
          preguntaId: "2020104010",
        },
      ],
      minimoParaAprobar: 7,
    },
    "2020301000e": {
    preguntas: [
      {
        id: "2020301001",
        pregunta: "¿Cuál de los siguientes tipos de almacenamiento es volátil y necesita suministro de electricidad?",
        opciones: ["Almacenamiento Secundario", "Almacenamiento Primario", "Memoria virtual", "Memoria caché"],
        correcta: 1,
        preguntaId: "2020301001",
      },
      {
        id: "2020301001",
        pregunta: "¿Qué técnica de memoria caché carga los datos antes de su lectura?",
        opciones: ["Write-Behind", "Prefetching", "Segmentación", "Zone Bit Recording"],
        correcta: 1,
        preguntaId: "2020301002",
      },
      {
        id: "2020301002",
        pregunta: "¿Qué tipo de acceso tienen las cintas magnéticas?",
        opciones: ["Acceso aleatorio", "Acceso secuencial", "Acceso directo", "Acceso indexado"],
        correcta: 1,
        preguntaId: "2020301003",
      },
      {
        id: "2020301003",
        pregunta: "¿De qué depende la capacidad de los dispositivos de almacenamiento óptico?",
        opciones: [
          "De la velocidad de rotación",
          "Del tamaño del disco",
          "De la longitud de onda del láser",
          "De la cantidad de surcos",
        ],
        correcta: 2,
        preguntaId: "2020301004",
      },
      {
        id: "2020301004",
        pregunta: "¿Qué tipo de memoria utilizan los discos SSD para almacenar datos?",
        opciones: ["Memoria RAM", "Memoria ROM", "Memoria NAND", "Memoria Cache"],
        correcta: 2,
        preguntaId: "2020301005",
      },
      {
        id: "2020301005",
        pregunta: "¿Cuántas líneas paralelas de datos puede manejar el protocolo NVME?",
        opciones: ["Hasta 32.000", "Hasta 64.000", "Hasta 128.000", "Hasta 256.000"],
        correcta: 1,
        preguntaId: "2020301006",
      },
      {
        id: "2020301006",
        pregunta: "¿Cuál de los siguientes tipos de memoria NAND almacena más bits por celda?",
        opciones: [
          "SLC (Single-Level Cell)",
          "MLC (Multi-Level Cell)",
          "TLC (Triple-Level Cell)",
          "QLC (Quad-Level Cell)",
        ],
        correcta: 3,
        preguntaId: "2020301007",
      },
      {
        id: "2020301006",
        pregunta:
          "¿Qué tipo de memoria NAND se utiliza en aplicaciones que requieren un rendimiento y confiabilidad excepcionales?",
        opciones: [
          "SLC (Single-Level Cell)",
          "MLC (Multi-Level Cell)",
          "TLC (Triple-Level Cell)",
          "QLC (Quad-Level Cell)",
        ],
        correcta: 0,
        preguntaId: "2020301008",
      },
      {
        id: "2020301007",
        pregunta:
          "¿Qué ventaja ofrece tener más de una cabina de almacenamiento distribuida en diferentes ubicaciones físicas?",
        opciones: [
          "Mayor capacidad de almacenamiento",
          "Menor costo de implementación",
          "Alta disponibilidad de la infraestructura",
          "Mejor rendimiento en la lectura de datos",
        ],
        correcta: 2,
        preguntaId: "2020301009",
      },
      {
        id: "2020301008",
        pregunta:
          "¿Qué tipo de tier de almacenamiento es más apropiado para aplicaciones en las que el tiempo de respuesta es crítico?",
        opciones: [
          "Tier bajo o de almacenamiento lento",
          "Tier medio o de almacenamiento rápido",
          "Tier alto o de almacenamiento ultrarrápido",
          "Tier híbrido",
        ],
        correcta: 2,
        preguntaId: "2020301010",
      },
      {
        id: "2020301009",
        pregunta: "¿Cuál de las siguientes NO es una medida mencionada para proteger contra ataques de ransomware?",
        opciones: [
          "Establecimiento de listas blancas y negras de ficheros",
          "Políticas adecuadas de snapshots preventivos",
          "Utilización de sistemas de detección de ataques",
          "Encriptación de todos los archivos",
        ],
        correcta: 3,
        preguntaId: "2020301011",
      },
    ],
    minimoParaAprobar: 8,
  },
  "2020302000e": {
    preguntas: [
      {
        id: "2020302001",
        pregunta: "¿Qué significa DAS en el contexto de almacenamiento?",
        opciones: ["Direct Access Storage", "Disk Array System", "Data Access System", "Directly Attached Storage"],
        correcta: 3,
        preguntaId: "2020302001",
      },
      {
        id: "2020302002",
        pregunta: "¿Cuántos dispositivos puede soportar cada conector de la placa base en el caso de dispositivos IDE?",
        opciones: ["Uno", "Dos", "Tres", "Cuatro"],
        correcta: 1,
        preguntaId: "2020302002",
      },
      {
        id: "2020302003",
        pregunta: "¿Cuál es la principal desventaja del modo de transferencia PIO en dispositivos IDE?",
        opciones: [
          "Es demasiado lento",
          "Requiere cables especiales",
          "Supone una sobrecarga importante para el procesador",
          "No es compatible con sistemas modernos",
        ],
        correcta: 2,
        preguntaId: "2020302003",
      },
      {
        id: "2020302004",
        pregunta: "¿Qué tipo de conexiones utiliza el estándar SATA?",
        opciones: [
          "Conexiones en bus",
          "Conexiones en estrella",
          "Conexiones directas punto a punto",
          "Conexiones en anillo",
        ],
        correcta: 2,
        preguntaId: "2020302004",
      },
      {
        id: "2020302005",
        pregunta: "¿Qué característica distingue a SCSI de IDE en términos de controladores?",
        opciones: [
          "SCSI no requiere controladores",
          "SCSI utiliza controladores más baratos",
          "SCSI dispone de controladoras inteligentes en cada dispositivo",
          "IDE tiene controladores más avanzados que SCSI",
        ],
        correcta: 2,
        preguntaId: "2020302005",
      },
      {
        id: "2020302006",
        pregunta: "¿Cuál fue la velocidad de transferencia inicial de las primeras implementaciones SCSI?",
        opciones: [
          "1,5 Megabytes por segundo",
          "3 Megabytes por segundo",
          "5 Megabytes por segundo",
          "10 Megabytes por segundo",
        ],
        correcta: 0,
        preguntaId: "2020302006",
      },
      {
        id: "2020302007",
        pregunta: "¿Cuál es la velocidad mínima de los discos SAS?",
        opciones: ["1 Gbps", "2 Gbps", "3 Gbps", "4 Gbps"],
        correcta: 2,
        preguntaId: "2020302007",
      },
      {
        id: "2020302008",
        pregunta: "En terminología SCSI, ¿qué se denomina 'initiator'?",
        opciones: [
          "El dispositivo de almacenamiento",
          "El punto de origen de la sesión SCSI",
          "El extremo que recibe los comandos",
          "La controladora SCSI",
        ],
        correcta: 1,
        preguntaId: "2020302008",
      },
      {
        id: "2020302009",
        pregunta: "¿Es posible conectar un disco SATA en un conector SAS?",
        opciones: [
          "No, nunca es posible",
          "Sí, pero con un adaptador especial",
          "Sí, es posible directamente",
          "Solo en sistemas antiguos",
        ],
        correcta: 2,
        preguntaId: "2020302009",
      },
      {
        id: "2020302010",
        pregunta: "¿Qué ventaja ofrecen los discos SAS sobre los SATA en términos de rendimiento?",
        opciones: [
          "Mayor capacidad de almacenamiento",
          "Menor consumo de energía",
          "Mayor velocidad de rotación y menor latencia",
          "Mejor compatibilidad con sistemas antiguos",
        ],
        correcta: 2,
        preguntaId: "2020302010",
      },
    ],
    minimoParaAprobar: 8,
  },
  "2020303000e": {
    preguntas: [
      {
        id: "2020303001",
        pregunta: "¿Qué protocolo es el más extendido para el acceso remoto a ficheros en sistemas Linux y Unix?",
        opciones: ["CIFS", "NFS", "SMB", "WebDAV"],
        correcta: 1,
        preguntaId: "2020303001",
      },
      {
        id: "2020303001",
        pregunta: "¿Qué puertos utiliza el servicio de red NFS a partir de su versión 4?",
        opciones: ["Solo el puerto 111", "Solo el puerto 2049", "Los puertos 111 y 2049", "El puerto 445"],
        correcta: 1,
        preguntaId: "2020303002",
      },
      {
        id: "2020303002",
        pregunta: "¿Dónde se define la configuración de recursos compartidos en un servidor NFS?",
        opciones: [
          "En el archivo /etc/fstab",
          "En el archivo /etc/exports",
          "En el archivo /etc/nfs.conf",
          "En el archivo /etc/shares",
        ],
        correcta: 1,
        preguntaId: "2020303003",
      },
      {
        id: "2020303003",
        pregunta: "¿Qué mejoras introduce NFSv4 según el texto?",
        opciones: [
          "Mayor velocidad de transferencia",
          "Mejoras en la gestión de los permisos a través de ACL",
          "Soporte para sistemas Windows",
          "Encriptación de datos",
        ],
        correcta: 1,
        preguntaId: "2020303004",
      },
      {
        id: "2020303005",
        pregunta: "¿Qué significa CIFS?",
        opciones: [
          "Common Internet File System",
          "Centralized Internet File Sharing",
          "Comprehensive Internet File Service",
          "Collaborative Internet File Storage",
        ],
        correcta: 0,
        preguntaId: "2020303005",
      },
      {
        id: "2020303006",
        pregunta: "¿Qué puerto utiliza CIFS/SMB para el tráfico?",
        opciones: ["Puerto 111", "Puerto 2049", "Puerto 445", "Puerto 80"],
        correcta: 2,
        preguntaId: "2020303006",
      },
      {
        id: "2020303007",
        pregunta: "¿Qué ha facilitado el desarrollo de nuevas librerías e integraciones para el almacenamiento remoto?",
        opciones: [
          "La aparición de nuevos sistemas operativos",
          "El aumento de la velocidad de las redes",
          "La aparición de servicios de almacenamiento cloud",
          "La obsolescencia de NFS y CIFS",
        ],
        correcta: 2,
        preguntaId: "2020303007",
      },
      {
        id: "2020303008",
        pregunta:
          "¿Cuál de los siguientes NO es un ejemplo de protocolo o tecnología mencionada para el almacenamiento remoto?",
        opciones: ["Protocolo S3 de Amazon", "SSHFS de Linux", "WebDAV", "FTP"],
        correcta: 3,
        preguntaId: "2020303008",
      },
      {
        id: "2020303004",
        pregunta: "¿Cómo se realiza un montaje NFS en sistemas Unix y Linux?",
        opciones: [
          "Usando el comando nfs-mount",
          "A través de la interfaz gráfica",
          "Usando el comando mount",
          "Editando el archivo /etc/fstab",
        ],
        correcta: 2,
        preguntaId: "2020303009",
      },
      {
        id: "2020303005",
        pregunta: "Además de compartir ficheros, ¿qué otros recursos puede compartir CIFS?",
        opciones: [
          "Solo impresoras",
          "Impresoras y puertos serie",
          "Impresoras y tarjetas de red",
          "Solo puertos serie",
        ],
        correcta: 1,
        preguntaId: "2020303010",
      },
    ],
    minimoParaAprobar: 8,
  },
  "2020304000e": {
    preguntas: [
      {
        id: "2020304001",
        pregunta: "¿Qué es un HBA en el contexto de almacenamiento SAN?",
        opciones: [
          "Un tipo de disco duro",
          "Un adaptador que facilita el acceso de un equipo a una SAN",
          "Un protocolo de comunicación",
          "Un tipo de cable de fibra óptica",
        ],
        correcta: 1,
        preguntaId: "2020304001",
      },
      {
        id: "2020304002",
        pregunta: "¿Cuál es el formato más extendido de transceptor en redes SAN?",
        opciones: ["RJ-45", "QSFP", "SFP", "XFP"],
        correcta: 2,
        preguntaId: "2020304002",
      },
      {
        id: "2020304003",
        pregunta: "¿Qué función principal cumplen los switches de SAN?",
        opciones: [
          "Almacenar datos",
          "Interconectar servidores o equipos finales con el servidor o cabina de almacenamiento",
          "Generar copias de seguridad",
          "Encriptar la información",
        ],
        correcta: 1,
        preguntaId: "2020304003",
      },
      {
        id: "2020304004",
        pregunta: "¿Qué se entiende por 'Storage Fabric' en una SAN?",
        opciones: [
          "Un tipo de disco duro",
          "El conjunto de redes de fibra óptica que interconexionan los switches",
          "Un protocolo de comunicación",
          "Un tipo de cable especial",
        ],
        correcta: 1,
        preguntaId: "2020304004",
      },
      {
        id: "2020304005",
        pregunta: "¿Qué es el 'zoning' en una SAN?",
        opciones: [
          "Un tipo de cable",
          "La segmentación en zonas de los puertos de fibra de los switches",
          "Un protocolo de comunicación",
          "Un método de encriptación",
        ],
        correcta: 1,
        preguntaId: "2020304005",
      },
      {
        id: "2020304006",
        pregunta: "¿Qué es un World Wide Name (WWN) en una SAN?",
        opciones: [
          "Un protocolo de comunicación",
          "Un tipo de cable",
          "Un código único que identifica a los dispositivos",
          "Un método de encriptación",
        ],
        correcta: 2,
        preguntaId: "2020304006",
      },
      {
        id: "2020304007",
        pregunta: "¿Qué es una LUN en el contexto de una SAN?",
        opciones: [
          "Un tipo de switch",
          "Un protocolo de comunicación",
          "Una dirección única que identifica un conjunto de bloques presentados como un disco único",
          "Un tipo de cable de fibra óptica",
        ],
        correcta: 2,
        preguntaId: "2020304007",
      },
      {
        id: "2020304008",
        pregunta: "¿Cuál de las siguientes NO es una técnica mencionada para mejorar la resiliencia de una SAN?",
        opciones: [
          "Establecimiento de estructura de red redundante",
          "Técnicas de mirroring de almacenamiento",
          "Infraestructura de Centro de Proceso de Datos adecuada",
          "Uso de un único switch central de alta capacidad",
        ],
        correcta: 3,
        preguntaId: "2020304008",
      },
      {
        id: "2020304009",
        pregunta: "¿Qué es el 'trunking' en el contexto de switches de fibra?",
        opciones: [
          "Un tipo de cable",
          "Un protocolo de comunicación",
          "La agrupación de más de un canal sobre la misma línea física",
          "Un método de encriptación",
        ],
        correcta: 2,
        preguntaId: "2020304009",
      },
      {
        id: "2020304010",
        pregunta: "¿Cuál de los siguientes NO es un protocolo mencionado para implementar SAN sobre IP?",
        opciones: ["iSCSI", "FCIP", "FCoE", "HTTP"],
        correcta: 3,
        preguntaId: "2020304010",
      },
      {
        id: "2020304011",
        pregunta: "¿Cuál es la principal diferencia entre NVMe y NVMe-oF?",
        opciones: [
          "NVMe-oF es más rápido que NVMe",
          "NVMe solo funciona con discos SSD",
          "NVMe transfiere comandos directamente a la memoria local, mientras NVMe-oF usa mensajes a través de la red",
          "NVMe-oF solo funciona con Fiber Channel",
        ],
        correcta: 2,
        preguntaId: "2020304011",
      },
    ],
    minimoParaAprobar: 9,
  },
  "2020305000e": {
    preguntas: [
      {
        id: "2020305001",
        pregunta: "¿Qué es LVM en el contexto de sistemas Linux?",
        opciones: [
          "Un tipo de sistema de archivos",
          "Una capa de abstracción que separa las características físicas del dispositivo de almacenamiento del sistema de ficheros final",
          "Un protocolo de red",
          "Un tipo de RAID",
        ],
        correcta: 1,
        preguntaId: "2020305001",
      },
      {
        id: "2020305001",
        pregunta: "¿Cuál de los siguientes NO es un concepto asociado con LVM?",
        opciones: ["Volumen físico (PV)", "Grupo de volúmenes (VG)", "Volumen lógico (LV)", "Volumen virtual (VV)"],
        correcta: 3,
        preguntaId: "2020305002",
      },
      {
        id: "2020305002",
        pregunta: "¿Cuál es una ventaja de utilizar LVM?",
        opciones: [
          "Aumenta la velocidad de lectura de los discos",
          "Permite la ampliación del sistema de ficheros incluyendo distintos dispositivos físicos",
          "Mejora la seguridad de los datos",
          "Reduce el consumo de energía de los discos",
        ],
        correcta: 1,
        preguntaId: "2020305003",
      },
      {
        id: "2020305003",
        pregunta: "¿Qué significa RAID?",
        opciones: [
          "Rapid Access to Independent Disks",
          "Redundant Array of Inexpensive Disks",
          "Random Access to Integrated Data",
          "Redundant Array of Independent Disks",
        ],
        correcta: 3,
        preguntaId: "2020305004",
      },
      {
        id: "2020305004",
        pregunta: "¿Qué es CRC en el contexto de RAID?",
        opciones: [
          "Control de Redundancia Cíclica",
          "Comprobación de Recursos Compartidos",
          "Control de Recuperación de Contenidos",
          "Comprobación de Rendimiento Continuo",
        ],
        correcta: 0,
        preguntaId: "2020305005",
      },
      {
        id: "2020305005",
        pregunta: "¿Cuál es una característica del RAID 0?",
        opciones: [
          "Proporciona redundancia de datos",
          "Mejora el tiempo de acceso a la información",
          "Requiere un mínimo de tres discos",
          "Escribe datos de paridad en dos unidades",
        ],
        correcta: 1,
        preguntaId: "2020305006",
      },
      {
        id: "2020305006",
        pregunta: "¿Qué tipo de RAID utiliza una configuración en espejo?",
        opciones: ["RAID 0", "RAID 1", "RAID 5", "RAID 6"],
        correcta: 1,
        preguntaId: "2020305007",
      },
      {
        id: "2020305007",
        pregunta: "¿Cuál de los siguientes tipos de RAID está actualmente en desuso?",
        opciones: ["RAID 0", "RAID 1", "RAID 3", "RAID 5"],
        correcta: 2,
        preguntaId: "2020305008",
      },
      {
        id: "2020305008",
        pregunta: "¿Cuál es una característica del RAID 5?",
        opciones: [
          "No proporciona redundancia de datos",
          "Requiere un mínimo de dos discos",
          "Los bloques de paridad se distribuyen a lo largo de todas las unidades",
          "Puede soportar la pérdida de dos discos sin perder datos",
        ],
        correcta: 2,
        preguntaId: "2020305009",
      },
      {
        id: "2020305009",
        pregunta: "¿Cuántos discos como mínimo requiere un RAID 6?",
        opciones: ["Dos", "Tres", "Cuatro", "Cinco"],
        correcta: 2,
        preguntaId: "2020305010",
      },
      {
        id: "2020305010",
        pregunta: "¿Cuál de los siguientes NO es un tipo de RAID combinado mencionado en el texto?",
        opciones: ["RAID 10", "RAID 01", "RAID 30", "RAID 60"],
        correcta: 3,
        preguntaId: "2020305011",
      },
    ],
    minimoParaAprobar: 8,
  },
  "2020401000e": {
    preguntas: [
      {
        id: "2020401001",
        pregunta: "¿Qué dispositivo se utiliza para transformar la imagen registrada en el CCD a formato digital?",
        opciones: ["Un espejo", "Un sensor", "Un conversor analógico-digital o DAC", "Una célula fotoeléctrica"],
        correcta: 2,
        preguntaId: "2020401001",
      },
      {
        id: "2020401002",
        pregunta: "¿Cuál es el estándar de escaneo más extendido, compatible con Windows y Linux?",
        opciones: ["WIA", "ISIS", "SANE", "TWAIN"],
        correcta: 3,
        preguntaId: "2020401002",
      },
      {
        id: "2020401003",
        pregunta: "¿Qué significa OCR en el contexto de digitalización de documentos?",
        opciones: [
          "Optical Color Recognition",
          "Optical Character Recognition",
          "Optical Content Reading",
          "Optical Conversion Resolution",
        ],
        correcta: 1,
        preguntaId: "2020401003",
      },
      {
        id: "2020401004",
        pregunta: "¿Cuál de los siguientes NO es un método mencionado para realizar compresión con pérdida?",
        opciones: [
          "Cambios de la paleta de colores",
          "Submuestreo de crominancia",
          "Codificación por transformación",
          "Compresión fractal",
        ],
        correcta: 3,
        preguntaId: "2020401004",
      },
      {
        id: "2020401005",
        pregunta:
          "Según la Norma Técnica de Interoperabilidad de Digitalización de Documentos, ¿cuál es la resolución mínima requerida para una imagen digitalizada?",
        opciones: [
          "100 píxeles por pulgada",
          "150 píxeles por pulgada",
          "200 píxeles por pulgada",
          "300 píxeles por pulgada",
        ],
        correcta: 2,
        preguntaId: "2020401005",
      },
      {
        id: "2020401006",
        pregunta:
          "¿Qué formato de imagen es comúnmente utilizado para animaciones y tiene una paleta limitada a 256 colores?",
        opciones: ["JPEG", "PNG", "GIF", "TIFF"],
        correcta: 2,
        preguntaId: "2020401006",
      },
      {
        id: "2020401007",
        pregunta:
          "¿Qué formato de imagen es propio del sistema operativo Windows y se usa para componentes como iconos y fondos de pantalla?",
        opciones: ["JPEG", "PNG", "GIF", "BMP"],
        correcta: 3,
        preguntaId: "2020401007",
      },
      {
        id: "2020401007",
        pregunta: "¿Cuál de los siguientes formatos de imagen siempre utiliza compresión sin pérdida (lossless)?",
        opciones: ["JPEG", "PNG", "TIFF", "BMP"],
        correcta: 1,
        preguntaId: "2020401008",
      },
      {
        id: "2020401007",
        pregunta:
          "¿Qué formato de imagen permite tanto compresión con pérdida como sin pérdida, dependiendo del método de compresión utilizado?",
        opciones: ["JPEG", "PNG", "TIFF", "GIF"],
        correcta: 2,
        preguntaId: "2020401009",
      },
      {
        id: "2020401007",
        pregunta: "¿Cuál es el ratio de compresión aceptable mencionado para el formato JPEG?",
        opciones: ["Hasta 5:1", "Hasta 10:1", "Hasta 15:1", "Hasta 20:1"],
        correcta: 1,
        preguntaId: "2020401010",
      },
    ],
    minimoParaAprobar: 8,
  },
  "2020402000e": {
    preguntas: [
      {
        id: "2020402001",
        pregunta: "¿Cómo se representa comúnmente la resolución de una pantalla?",
        opciones: [
          "Resolución vertical x resolución horizontal",
          "Resolución horizontal x resolución vertical",
          "Número total de píxeles",
          "Diagonal de la pantalla en pulgadas",
        ],
        correcta: 1,
        preguntaId: "2020402001",
      },
      {
        id: "2020402002",
        pregunta: "¿Qué resolución corresponde a Full HD?",
        opciones: ["1280x720", "1920x1080", "2560x1440", "3840x2160"],
        correcta: 1,
        preguntaId: "2020402002",
      },
      {
        id: "2020402003",
        pregunta: "¿Cuál era uno de los problemas de los monitores CRT?",
        opciones: [
          "Bajo consumo de energía",
          "Tamaño compacto",
          "Necesidad de tiempo de calentamiento",
          "Inmunidad a campos magnéticos",
        ],
        correcta: 2,
        preguntaId: "2020402003",
      },
      {
        id: "2020402004",
        pregunta: "¿Qué tipo de gas se utilizaba comúnmente en las pantallas de plasma?",
        opciones: ["Argón", "Neón", "Xenón", "Helio"],
        correcta: 1,
        preguntaId: "2020402004",
      },
      {
        id: "2020402005",
        pregunta: "En las pantallas LCD, ¿cuántos subpíxeles tiene cada pixel?",
        opciones: ["Dos", "Tres", "Cuatro", "Cinco"],
        correcta: 1,
        preguntaId: "2020402005",
      },
      {
        id: "2020402006",
        pregunta: "¿Por qué las pantallas LED fueron inicialmente populares para uso al aire libre?",
        opciones: [
          "Por su bajo consumo de energía",
          "Por su tamaño compacto",
          "Por su brillo que permite ver bien la imagen a la luz del sol",
          "Por su resistencia al agua",
        ],
        correcta: 2,
        preguntaId: "2020402006",
      },
      {
        id: "2020402007",
        pregunta: "¿Cuál es el formato de pantalla más tradicional mencionado en el texto?",
        opciones: ["16:9", "4:3", "21:9", "3:2"],
        correcta: 1,
        preguntaId: "2020402007",
      },
      {
        id: "2020402002",
        pregunta: "¿Cuál de las siguientes resoluciones tiene la mayor densidad de píxeles?",
        opciones: ["QVGA (320x240)", "VGA (640x480)", "HD (1280x720)", "4K (4096x3072)"],
        correcta: 3,
        preguntaId: "2020402008",
      },
      {
        id: "2020402004",
        pregunta: "¿Qué problema comparten las pantallas CRT y de plasma?",
        opciones: ["Bajo brillo", "Screen burn-in o quemado de pantalla", "Corta vida útil", "Alto consumo de energía"],
        correcta: 1,
        preguntaId: "2020402009",
      },
      {
        id: "2020402007",
        pregunta: "¿Cuál es el formato de pantalla comúnmente denominado como 'panorámico'?",
        opciones: ["4:3", "16:9", "21:9", "3:2"],
        correcta: 1,
        preguntaId: "2020402010",
      },
    ],
    minimoParaAprobar: 8,
  },
  
  }
  
  