export const preguntas = {
  "2050101000e": {
    preguntas: [
      {
        id: "2050101001",
        pregunta: "¿Cuál de las siguientes NO es una característica de los datos en una base de datos?",
        opciones: ["Integrados", "Estructurados", "Con redundancia ilimitada", "Relacionados"],
        correcta: 2,
        preguntaId: "2050101001",
      },
      {
        id: "2050101001",
        pregunta: "¿Qué significa que los datos en una base de datos deben estar 'integrados'?",
        opciones: [
          "Deben estar dispersos en múltiples ubicaciones",
          "La definición y descripción de los datos deben ser únicas y estar integradas con los mismos datos",
          "Deben estar encriptados",
          "Deben estar en formato binario",
        ],
        correcta: 1,
        preguntaId: "2050101002",
      },
      {
        id: "2050101001",
        pregunta: "¿Qué tipo de redundancia se permite en una base de datos por motivos de eficiencia?",
        opciones: [
          "Redundancia lógica",
          "Redundancia física",
          "Redundancia total",
          "No se permite ningún tipo de redundancia",
        ],
        correcta: 1,
        preguntaId: "2050101003",
      },
      {
        id: "2050101002",
        pregunta: "¿Qué es un Sistema Gestor de Base de Datos (SGBD)?",
        opciones: [
          "Un tipo de base de datos",
          "Un conjunto de datos estructurados",
          "Un conjunto de programas para gestionar bases de datos",
          "Un lenguaje de programación",
        ],
        correcta: 2,
        preguntaId: "2050101004",
      },
      {
        id: "2050101002",
        pregunta: "¿Cuál de las siguientes NO es una función de los SGBD?",
        opciones: [
          "Mantener la integridad de los datos",
          "Administrar el acceso de los usuarios a los datos",
          "Crear contenido para la base de datos",
          "Recuperar la información si el sistema se corrompe",
        ],
        correcta: 2,
        preguntaId: "2050101005",
      },
      {
        id: "2050101003",
        pregunta: "¿Qué subsistema del SGBD es la interfaz principal del usuario con la base de datos?",
        opciones: [
          "Motor de la base de datos",
          "Subsistema de definición de datos",
          "Subsistema de manipulación de datos",
          "Subsistema de administración",
        ],
        correcta: 2,
        preguntaId: "2050101006",
      },
      {
        id: "2050101003",
        pregunta: "¿Qué función realiza el motor de la base de datos en un SGBD?",
        opciones: [
          "Genera informes",
          "Administra el acceso de usuarios",
          "Convierte peticiones lógicas en su equivalente físico",
          "Define la estructura del fichero",
        ],
        correcta: 2,
        preguntaId: "2050101007",
      },
      {
        id: "2050101004",
        pregunta: "¿Cuál de las siguientes NO es una característica principal de los SGBD?",
        opciones: [
          "Manejo de grandes volúmenes de datos",
          "Baja disponibilidad",
          "Escalabilidad",
          "Seguridad y control de accesos",
        ],
        correcta: 1,
        preguntaId: "2050101008",
      },
      {
        id: "2050101004",
        pregunta:
          "¿Qué característica de los SGBD se refiere a su capacidad para manejar múltiples usuarios accediendo simultáneamente a los datos?",
        opciones: ["Alta disponibilidad", "Manejo de accesos concurrentes", "Escalabilidad", "Flexibilidad"],
        correcta: 1,
        preguntaId: "2050101009",
      },
      {
        id: "2050101003",
        pregunta: "¿Qué subsistema del SGBD ayuda a crear y mantener el diccionario de datos?",
        opciones: [
          "Subsistema de definición de datos",
          "Subsistema de manipulación de datos",
          "Subsistema de generación de aplicaciones",
          "Subsistema de administración",
        ],
        correcta: 0,
        preguntaId: "2050101010",
      },
      {
        id: "2050101001",
        pregunta:
          "¿Qué característica de los datos en una base de datos se refiere a que deben reflejar las interrelaciones y restricciones existentes en el mundo real?",
        opciones: ["Integrados", "Estructurados", "Relacionados", "Independientes"],
        correcta: 1,
        preguntaId: "2050101011",
      },
      {
        id: "2050101002",
        pregunta: "¿Qué permite un SGBD en cuanto a la modificación y extracción de información?",
        opciones: [
          "Solo permite la extracción de información",
          "Solo permite la modificación de información",
          "Permite la modificación y extracción mediante órdenes complejas",
          "Permite la modificación y extracción mediante órdenes sencillas o algún lenguaje de consultas",
        ],
        correcta: 3,
        preguntaId: "2050101012",
      },
      {
        id: "2050101003",
        pregunta:
          "¿Qué subsistema del SGBD contiene utilidades para ayudar a los usuarios en el desarrollo de aplicaciones?",
        opciones: [
          "Subsistema de definición de datos",
          "Subsistema de manipulación de datos",
          "Subsistema de generación de aplicaciones",
          "Subsistema de administración",
        ],
        correcta: 2,
        preguntaId: "2050101013",
      },
      {
        id: "2050101004",
        pregunta: "¿Qué característica de los SGBD se refiere a su capacidad de crecer y adaptarse a mayores demandas?",
        opciones: ["Alta disponibilidad", "Manejo de accesos concurrentes", "Escalabilidad", "Flexibilidad"],
        correcta: 2,
        preguntaId: "2050101014",
      },
      {
        id: "2050101004",
        pregunta: "¿Qué característica de los SGBD asegura que los datos permanezcan consistentes y correctos?",
        opciones: ["Seguridad y control de accesos", "Integridad de los datos", "Documentación", "Flexibilidad"],
        correcta: 1,
        preguntaId: "2050101015",
      },
    ],
    minimoParaAprobar: 12,
  },
  "2050201000e": {
    preguntas: [
      {
        id: "2050201001",
        pregunta: "¿Quién propuso el modelo relacional para el modelado y la gestión de bases de datos?",
        opciones: ["Bill Gates", "Steve Jobs", "E.F Codd", "Tim Berners-Lee"],
        correcta: 2,
        preguntaId: "2050201001",
      },
      {
        id: "2050201002",
        pregunta: "¿Qué representa una tupla en el modelo relacional?",
        opciones: [
          "Una columna de la tabla",
          "Una fila de la tabla",
          "El nombre de la tabla",
          "El tipo de datos de un campo",
        ],
        correcta: 1,
        preguntaId: "2050201002",
      },
      {
        id: "2050201003",
        pregunta: "¿Qué es el grado de una tabla en el modelo relacional?",
        opciones: [
          "El número de tuplas que almacena",
          "El número de campos que posee",
          "El número de claves primarias",
          "El número de relaciones con otras tablas",
        ],
        correcta: 1,
        preguntaId: "2050201003",
      },
      {
        id: "2050201004",
        pregunta: "¿Qué es una clave foránea (FK) en el modelo relacional?",
        opciones: [
          "Un atributo único en cada tupla",
          "Una columna que es clave principal en una tabla relacionada",
          "Un atributo que no puede ser nulo",
          "La primera columna de una tabla",
        ],
        correcta: 1,
        preguntaId: "2050201004",
      },
      {
        id: "2050201005",
        pregunta: "Según la regla de integridad de entidad, ¿qué característica debe cumplir la clave primaria?",
        opciones: [
          "Puede contener valores nulos",
          "Debe ser única pero puede repetirse",
          "No puede contener valores nulos",
          "Debe ser siempre un número entero",
        ],
        correcta: 2,
        preguntaId: "2050201005",
      },
      {
        id: "2050201006",
        pregunta: "¿Qué establece la regla de integridad referencial?",
        opciones: [
          "Que todas las claves foráneas deben ser únicas",
          "Que las claves foráneas deben ser valores nulos o existir en la clave primaria referenciada",
          "Que no puede haber claves foráneas en una tabla",
          "Que las claves primarias deben ser siempre numéricas",
        ],
        correcta: 1,
        preguntaId: "2050201006",
      },
      {
        id: "2050201007",
        pregunta: "¿Qué establece la regla de integridad de dominio?",
        opciones: [
          "Que todos los campos deben ser de tipo texto",
          "Que no se pueden usar claves foráneas",
          "La validez de las restricciones que debe cumplir una determinada columna de la tabla",
          "Que todas las tablas deben tener al menos 10 columnas",
        ],
        correcta: 2,
        preguntaId: "2050201007",
      },
      {
        id: "2050201008",
        pregunta: "¿Qué tipo de restricción permite acotar los valores del dominio de un atributo?",
        opciones: [
          "Restricción de tupla",
          "Restricción de tabla",
          "Restricción de atributo",
          "Restricción de base de datos",
        ],
        correcta: 2,
        preguntaId: "2050201008",
      },
      {
        id: "2050201003",
        pregunta: "¿Qué representa la cardinalidad en una tabla del modelo relacional?",
        opciones: [
          "El número de campos que posee",
          "El número de tuplas que almacena",
          "El número de claves primarias",
          "El número de relaciones con otras tablas",
        ],
        correcta: 1,
        preguntaId: "2050201009",
      },
      {
        id: "2050201004",
        pregunta: "¿Cuál de las siguientes NO es una característica de las tuplas en una tabla relacional?",
        opciones: [
          "No se permite la repetición de tuplas en una misma tabla",
          "Las tuplas tienen un orden determinado",
          "Cada tupla corresponde a un registro de la tabla",
          "Las tuplas describen entidades o relaciones particulares",
        ],
        correcta: 1,
        preguntaId: "2050201010",
      },
      {
        id: "2050201005",
        pregunta: "Si una clave primaria es compuesta, según la regla de integridad de entidad, ¿qué debe cumplirse?",
        opciones: [
          "Al menos uno de los campos puede ser nulo",
          "Todos los campos deben ser nulos",
          "Ningún campo de la combinación puede ser nulo",
          "Solo el primer campo no puede ser nulo",
        ],
        correcta: 2,
        preguntaId: "2050201011",
      },
      {
        id: "2050201007",
        pregunta: "¿Qué significa 'NOT NULL' en la creación de una tabla?",
        opciones: [
          "Que la columna debe contener solo valores nulos",
          "Que la columna no puede contener valores nulos",
          "Que la columna es la clave primaria",
          "Que la columna es una clave foránea",
        ],
        correcta: 1,
        preguntaId: "2050201012",
      },
      {
        id: "2050201008",
        pregunta:
          "¿Qué tipo de restricción permite comprobar que los valores de algunos atributos de una misma tupla son consistentes entre sí?",
        opciones: [
          "Restricción de atributo",
          "Restricción de tupla",
          "Restricción de tabla",
          "Restricción de base de datos",
        ],
        correcta: 1,
        preguntaId: "2050201013",
      },
      {
        id: "2050201008",
        pregunta: "¿Qué tipo de restricción se realiza a través de permisos de usuario sobre las tablas?",
        opciones: ["Restricción de atributo", "Restricción de tupla", "Restricción de tabla", "Restricción de usuario"],
        correcta: 3,
        preguntaId: "2050201014",
      },
      {
        id: "2050201002",
        pregunta: "¿En qué se basa el modelo relacional?",
        opciones: [
          "En la programación orientada a objetos",
          "En el concepto matemático de Relación",
          "En la estructura de árbol",
          "En el modelo de red",
        ],
        correcta: 1,
        preguntaId: "2050201015",
      },
    ],
    minimoParaAprobar: 12,
  },
  "2050301000e": {
    preguntas: [
      {
        id: "2050301001",
        pregunta: "¿Qué es un sistema de gestión de bases de datos relacionales (SGBDR o RDBMS)?",
        opciones: [
          "Un sistema que sigue el modelo de red",
          "Un sistema que sigue el modelo jerárquico",
          "Un sistema que sigue el modelo relacional",
          "Un sistema que sigue el modelo orientado a objetos",
        ],
        correcta: 2,
        preguntaId: "2050301001",
      },
      {
        id: "2050301002",
        pregunta:
          "¿Quién publicó las 12 reglas (que en realidad son 13) para evaluar si un SGBD puede considerarse relacional?",
        opciones: ["Bill Gates", "Steve Jobs", "Edgar F. Codd", "Tim Berners-Lee"],
        correcta: 2,
        preguntaId: "2050301002",
      },
      {
        id: "2050301003",
        pregunta: "Según la Regla 0 de Codd, ¿qué debe usar un sistema para ser considerado relacional?",
        opciones: [
          "Únicamente sus capacidades relacionales",
          "Una combinación de capacidades relacionales y no relacionales",
          "Cualquier capacidad que permita gestionar una base de datos",
          "Exclusivamente SQL",
        ],
        correcta: 0,
        preguntaId: "2050301003",
      },
      {
        id: "2050301004",
        pregunta: "¿Qué establece la Regla 1 de Codd (Regla de la Información)?",
        opciones: [
          "Todos los datos deben estar en archivos separados",
          "Toda la información debe estar representada explícitamente en el esquema lógico",
          "La información debe estar distribuida en múltiples bases de datos",
          "Los datos deben estar encriptados",
        ],
        correcta: 1,
        preguntaId: "2050301004",
      },
      {
        id: "2050301005",
        pregunta: "Según la Regla 2 de Codd, ¿cómo se debe poder acceder a cada dato en una base de datos relacional?",
        opciones: [
          "Solo por el nombre de la tabla",
          "Por una combinación de nombre de tabla, valor de clave primaria y nombre de columna",
          "Únicamente por el valor de la clave primaria",
          "Por el nombre de la base de datos",
        ],
        correcta: 1,
        preguntaId: "2050301005",
      },
      {
        id: "2050301006",
        pregunta: "¿Qué tipo de lógica utilizan muchas bases de datos relacionales para manejar valores nulos?",
        opciones: ["Lógica booleana", "Lógica difusa", "Lógica trivaluada", "Lógica modal"],
        correcta: 2,
        preguntaId: "2050301006",
      },
      {
        id: "2050301007",
        pregunta: "Según la Regla 4 de Codd, ¿cómo se representa la descripción de la base de datos?",
        opciones: [
          "En un archivo separado",
          "De la misma manera que los datos normales",
          "En una base de datos separada",
          "En código fuente del SGBD",
        ],
        correcta: 1,
        preguntaId: "2050301007",
      },
      {
        id: "2050301008",
        pregunta:
          "¿Qué lenguaje cumple en gran medida con la Regla 5 de Codd (Regla del Sublenguaje de Datos Completo)?",
        opciones: ["Java", "C++", "Python", "SQL"],
        correcta: 3,
        preguntaId: "2050301008",
      },
      {
        id: "2050301009",
        pregunta: "¿Qué establece la Regla 6 de Codd sobre las vistas?",
        opciones: [
          "Todas las vistas deben ser de solo lectura",
          "Las vistas no deben utilizarse en un sistema relacional",
          "Todas las vistas que son teóricamente actualizables se deben actualizar por el sistema",
          "Las vistas solo pueden ser creadas por administradores",
        ],
        correcta: 2,
        preguntaId: "2050301009",
      },
      {
        id: "2050301010",
        pregunta: "Según la Regla 7 de Codd, ¿cómo debe ser el lenguaje de manejo de datos?",
        opciones: ["De bajo nivel", "De alto nivel (de conjuntos)", "Orientado a objetos", "Basado en procedimientos"],
        correcta: 1,
        preguntaId: "2050301010",
      },
      {
        id: "2050301011",
        pregunta: "¿Qué establece la Regla 8 de Codd (Regla de Independencia Física de Datos)?",
        opciones: [
          "Los programas de aplicación deben cambiar cuando cambia la representación física de los datos",
          "Los programas de aplicación permanecen inalterados a nivel físico cuando se realizan cambios en las representaciones de almacenamiento",
          "Los datos físicos y lógicos deben estar siempre sincronizados",
          "Los cambios físicos siempre requieren cambios lógicos",
        ],
        correcta: 1,
        preguntaId: "2050301011",
      },
      {
        id: "2050301012",
        pregunta: "¿Qué tipo de cambios permite la Regla 9 de Codd sin afectar a los programas de aplicación?",
        opciones: [
          "Cambios que no preservan la información",
          "Cambios que alteran completamente la estructura de la base de datos",
          "Cambios a las tablas base que preserven la información",
          "Cambios que eliminan datos",
        ],
        correcta: 2,
        preguntaId: "2050301012",
      },
      {
        id: "2050301013",
        pregunta: "Según la Regla 10 de Codd, ¿dónde deben definirse los limitantes de integridad?",
        opciones: [
          "En los programas de aplicación",
          "En el sublenguaje de datos relacional y almacenados en el catálogo",
          "En un archivo de configuración separado",
          "En el sistema operativo",
        ],
        correcta: 1,
        preguntaId: "2050301013",
      },
      {
        id: "2050301014",
        pregunta: "¿Qué establece la Regla 11 de Codd sobre la independencia de distribución?",
        opciones: [
          "Las bases de datos relacionales no pueden ser distribuidas",
          "Las mismas órdenes y programas se ejecutan igual en una BD centralizada que en una distribuida",
          "Las bases de datos distribuidas requieren un lenguaje de consulta especial",
          "La distribución de datos siempre afecta al rendimiento de las consultas",
        ],
        correcta: 1,
        preguntaId: "2050301014",
      },
      {
        id: "2050301015",
        pregunta: "¿Qué prohíbe la Regla 12 de Codd (Regla de la No Subversión)?",
        opciones: [
          "El uso de lenguajes de alto nivel",
          "La creación de vistas",
          "El uso de un lenguaje de bajo nivel para saltarse las reglas de integridad",
          "La modificación de la estructura de la base de datos",
        ],
        correcta: 2,
        preguntaId: "2050301015",
      },
    ],
    minimoParaAprobar: 12,
  },
  "2050401000e": {
    preguntas: [
      {
        id: "2050401001",
        pregunta: "¿Cuáles son los objetivos principales de la normalización de bases de datos?",
        opciones: [
          "Aumentar la redundancia y complicar la actualización de datos",
          "Evitar redundancia, simplificar la actualización de datos y garantizar la integridad referencial",
          "Crear más tablas y aumentar el tamaño de la base de datos",
          "Eliminar todas las relaciones entre tablas",
        ],
        correcta: 1,
        preguntaId: "2050401001",
      },
      {
        id: "2050401002",
        pregunta: "¿Qué es una dependencia funcional transitiva?",
        opciones: [
          "Si X → Y entonces XZ → YZ",
          "Si Y está incluido en X entonces X → Y",
          "Si X → Y → Z entonces X → Z",
          "Es una conexión entre uno o más atributos",
        ],
        correcta: 2,
        preguntaId: "2050401002",
      },
      {
        id: "2050401003",
        pregunta: "¿Cuál de las siguientes NO es una característica de la Primera Forma Normal (1FN)?",
        opciones: [
          "Todos los atributos son atómicos",
          "No debe existir variación en el número de columnas",
          "Los campos clave deben identificarse por los campos no clave",
          "Debe existir una independencia del orden tanto de las filas como de las columnas",
        ],
        correcta: 2,
        preguntaId: "2050401003",
      },
      {
        id: "2050401004",
        pregunta: "¿Qué condición debe cumplir una tabla para estar en Segunda Forma Normal (2FN)?",
        opciones: [
          "Debe estar en 1FN y no tener dependencias parciales",
          "Debe tener una clave primaria compuesta",
          "Todos los atributos deben depender de una parte de la clave primaria",
          "No debe tener atributos no clave",
        ],
        correcta: 0,
        preguntaId: "2050401004",
      },
      {
        id: "2050401005",
        pregunta: "¿Qué característica define la Tercera Forma Normal (3FN)?",
        opciones: [
          "Elimina las dependencias transitivas",
          "Elimina las dependencias parciales",
          "Elimina las dependencias multivaluadas",
          "Elimina las dependencias de reunión",
        ],
        correcta: 0,
        preguntaId: "2050401005",
      },
      {
        id: "2050401006",
        pregunta: "¿Qué condición debe cumplir una tabla para estar en Forma Normal de Boyce-Codd (FNBC)?",
        opciones: [
          "Debe estar en 3FN",
          "Cada determinante debe ser una clave candidata",
          "No debe tener dependencias multivaluadas",
          "Debe eliminar todas las dependencias funcionales",
        ],
        correcta: 1,
        preguntaId: "2050401006",
      },
      {
        id: "2050401007",
        pregunta: "¿Qué elimina la Cuarta Forma Normal (4FN)?",
        opciones: [
          "Dependencias parciales",
          "Dependencias transitivas",
          "Dependencias multivaluadas no triviales",
          "Dependencias de reunión",
        ],
        correcta: 2,
        preguntaId: "2050401007",
      },
      {
        id: "2050401008",
        pregunta: "¿Cuándo se considera que una tabla está en Quinta Forma Normal (5FN)?",
        opciones: [
          "Cuando está en 4FN y no tiene dependencias de reunión no triviales",
          "Cuando elimina todas las dependencias funcionales",
          "Cuando todos sus atributos son clave primaria",
          "Cuando no tiene ninguna dependencia funcional",
        ],
        correcta: 0,
        preguntaId: "2050401008",
      },
      {
        id: "2050401003",
        pregunta: "¿Qué acción se realiza para llevar una tabla a Primera Forma Normal (1FN)?",
        opciones: [
          "Eliminar las dependencias transitivas",
          "Crear una tabla independiente para cada conjunto de datos relacionados",
          "Eliminar todas las claves foráneas",
          "Combinar múltiples tablas en una sola",
        ],
        correcta: 1,
        preguntaId: "2050401009",
      },
      {
        id: "2050401004",
        pregunta: "En el contexto de la Segunda Forma Normal (2FN), ¿qué es una dependencia parcial?",
        opciones: [
          "Cuando un atributo no clave depende de toda la clave primaria",
          "Cuando un atributo no clave depende de una parte de la clave primaria compuesta",
          "Cuando un atributo clave depende de un atributo no clave",
          "Cuando dos atributos no clave dependen uno del otro",
        ],
        correcta: 1,
        preguntaId: "2050401010",
      },
      {
        id: "2050401005",
        pregunta: "¿Por qué no siempre es práctico cumplir estrictamente con la Tercera Forma Normal (3FN)?",
        opciones: [
          "Porque puede llevar a la creación de demasiadas tablas",
          "Porque elimina todas las relaciones entre tablas",
          "Porque hace que las consultas sean más lentas",
          "Porque aumenta la redundancia de datos",
        ],
        correcta: 0,
        preguntaId: "2050401011",
      },
      {
        id: "2050401006",
        pregunta:
          "¿Cuál es la principal diferencia entre la Tercera Forma Normal (3FN) y la Forma Normal de Boyce-Codd (FNBC)?",
        opciones: [
          "La FNBC elimina las dependencias multivaluadas",
          "La FNBC es una versión más débil que la 3FN",
          "La FNBC requiere que cada determinante sea una clave candidata",
          "La FNBC se aplica solo a tablas con claves compuestas",
        ],
        correcta: 2,
        preguntaId: "2050401012",
      },
      {
        id: "2050401007",
        pregunta: "¿Qué tipo de dependencia aborda específicamente la Cuarta Forma Normal (4FN)?",
        opciones: [
          "Dependencias funcionales",
          "Dependencias parciales",
          "Dependencias transitivas",
          "Dependencias multivaluadas",
        ],
        correcta: 3,
        preguntaId: "2050401013",
      },
      {
        id: "2050401008",
        pregunta: "¿En qué situaciones se suele aplicar la Quinta Forma Normal (5FN)?",
        opciones: [
          "En todas las bases de datos relacionales",
          "Solo en bases de datos muy pequeñas",
          "En casos complejos para garantizar la integridad de datos",
          "Únicamente en bases de datos distribuidas",
        ],
        correcta: 2,
        preguntaId: "2050401014",
      },
      {
        id: "2050401001",
        pregunta: "¿Cuál de las siguientes afirmaciones es correcta sobre las tablas en una base de datos relacional?",
        opciones: [
          "Pueden tener filas duplicadas",
          "Los datos en una columna pueden ser de diferentes tipos",
          "Cada tabla debe tener un nombre único",
          "El orden de las columnas es importante para su significado",
        ],
        correcta: 2,
        preguntaId: "2050401015",
      },
    ],
    minimoParaAprobar: 12,
  },
  "2050501000e": {
    preguntas: [
      {
        id: "2050501001",
        pregunta: "¿Cuáles son los cuatro principios del modelo ACID?",
        opciones: [
          "Atomicidad, Consistencia, Integridad, Durabilidad",
          "Atomicidad, Consistencia, Aislamiento, Durabilidad",
          "Accesibilidad, Consistencia, Integridad, Disponibilidad",
          "Atomicidad, Coherencia, Independencia, Distribución",
        ],
        correcta: 1,
        preguntaId: "2050501001",
      },
      {
        id: "2050501002",
        pregunta: "¿Qué establece el principio de Atomicidad en el modelo ACID?",
        opciones: [
          "Las transacciones deben ser divisibles en partes más pequeñas",
          "Las transacciones deben seguir una regla de 'todo o nada'",
          "Las transacciones deben ser lo más pequeñas posible",
          "Las transacciones deben ser indivisibles a nivel atómico",
        ],
        correcta: 1,
        preguntaId: "2050501002",
      },
      {
        id: "2050501003",
        pregunta:
          "Según el principio de Consistencia, ¿qué ocurre si una transacción viola las reglas de consistencia de la base de datos?",
        opciones: [
          "La transacción se ejecuta parcialmente",
          "La transacción se ejecuta completamente, pero se marca como inconsistente",
          "La transacción completa se revierte y la base de datos se restaura a un estado consistente",
          "Se permite la inconsistencia para mantener la disponibilidad de los datos",
        ],
        correcta: 2,
        preguntaId: "2050501003",
      },
      {
        id: "2050501004",
        pregunta: "¿Qué garantiza el principio de Aislamiento en el modelo ACID?",
        opciones: [
          "Que las transacciones se ejecuten en orden cronológico",
          "Que las transacciones múltiples que ocurren al mismo tiempo no afecten la ejecución del otro",
          "Que las transacciones se ejecuten en servidores aislados",
          "Que cada transacción tenga su propia copia de la base de datos",
        ],
        correcta: 1,
        preguntaId: "2050501004",
      },
      {
        id: "2050501005",
        pregunta: "¿Cómo se garantiza la Durabilidad en el modelo ACID?",
        opciones: [
          "Mediante el uso de hardware de alta durabilidad",
          "A través de transacciones de larga duración",
          "Mediante el uso de copias de seguridad de la base de datos y registros de transacciones",
          "Utilizando sistemas de almacenamiento en la nube",
        ],
        correcta: 2,
        preguntaId: "2050501005",
      },
      {
        id: "2050501006",
        pregunta: "¿Qué establece el teorema CAP?",
        opciones: [
          "Que todas las bases de datos deben cumplir con el modelo ACID",
          "Que es imposible que un almacén de datos distribuido proporcione simultáneamente más de dos de las tres garantías: Consistencia, Disponibilidad y Tolerancia de partición",
          "Que las bases de datos NoSQL son superiores a las bases de datos relacionales",
          "Que la Consistencia, Disponibilidad y Tolerancia de partición pueden lograrse simultáneamente en cualquier sistema de base de datos",
        ],
        correcta: 1,
        preguntaId: "2050501006",
      },
      {
        id: "2050501007",
        pregunta: "En el contexto del teorema CAP, ¿qué implica la Tolerancia de partición?",
        opciones: [
          "Que el sistema puede dividirse en particiones más pequeñas",
          "Que el sistema continúa funcionando a pesar de que la red deje caer o retrase mensajes entre nodos",
          "Que el sistema puede tolerar la pérdida de datos",
          "Que el sistema puede funcionar con particiones de datos inconsistentes",
        ],
        correcta: 1,
        preguntaId: "2050501007",
      },
      {
        id: "2050501001",
        pregunta: "¿Cuál de las siguientes NO es una característica del modelo ACID?",
        opciones: ["Atomicidad", "Consistencia", "Aislamiento", "Distribución"],
        correcta: 3,
        preguntaId: "2050501008",
      },
      {
        id: "2050501006",
        pregunta: "¿Qué tipo de bases de datos generalmente no proporcionan todos los conceptos de ACID?",
        opciones: [
          "Bases de datos relacionales",
          "Bases de datos NoSQL",
          "Bases de datos orientadas a objetos",
          "Bases de datos jerárquicas",
        ],
        correcta: 1,
        preguntaId: "2050501009",
      },
      {
        id: "2050501007",
        pregunta:
          "Según el teorema CAP, en caso de un fallo de red, ¿entre qué debe elegir el diseñador de la base de datos?",
        opciones: [
          "Consistencia y Aislamiento",
          "Disponibilidad y Durabilidad",
          "Consistencia y Disponibilidad",
          "Atomicidad y Tolerancia de partición",
        ],
        correcta: 2,
        preguntaId: "2050501010",
      },
      {
        id: "2050501007",
        pregunta:
          "¿Qué solución ofrece generalmente un modelo de base de datos relacional como MySQL o Oracle en caso de un fallo de red?",
        opciones: [
          "Continuar la operación arriesgando inconsistencia de datos",
          "Cancelar la operación, disminuyendo la disponibilidad pero garantizando la coherencia",
          "Ignorar completamente la consistencia de datos",
          "Duplicar los datos en múltiples servidores",
        ],
        correcta: 1,
        preguntaId: "2050501011",
      },
      {
        id: "2050501007",
        pregunta:
          "¿Qué tipo de base de datos se podría utilizar si se decide continuar con la operación arriesgando inconsistencia de datos?",
        opciones: [
          "Base de datos relacional como MySQL",
          "Base de datos NoSQL como Redis o MongoDB",
          "Base de datos orientada a objetos",
          "Base de datos jerárquica",
        ],
        correcta: 1,
        preguntaId: "2050501012",
      },
      {
        id: "2050501002",
        pregunta:
          "Si una parte de una transacción falla en un sistema que sigue el principio de Atomicidad, ¿qué sucede?",
        opciones: [
          "Solo la parte fallida de la transacción se revierte",
          "La transacción completa falla",
          "La transacción se completa parcialmente",
          "El sistema intenta automáticamente corregir la parte fallida",
        ],
        correcta: 1,
        preguntaId: "2050501013",
      },
      {
        id: "2050501004",
        pregunta:
          "En el contexto del Aislamiento, si dos transacciones ocurren simultáneamente, ¿qué garantiza el sistema?",
        opciones: [
          "Que ambas transacciones se ejecutarán al mismo tiempo",
          "Que la transacción más importante se ejecutará primero",
          "Que las transacciones no interferirán entre sí",
          "Que ambas transacciones se combinarán en una sola",
        ],
        correcta: 2,
        preguntaId: "2050501014",
      },
      {
        id: "2050501007",
        pregunta:
          "¿Qué bases de datos NoSQL podrían utilizarse si se decide continuar con la operación sin importar en absoluto la consistencia de datos?",
        opciones: ["MySQL y Oracle", "MongoDB y Redis", "Cassandra, CouchDB o DynamoDB", "SQL Server y PostgreSQL"],
        correcta: 2,
        preguntaId: "2050501015",
      },
    ],
    minimoParaAprobar: 12,
  },
  "2050601000e": {
    preguntas: [
      {
        id: "2050601001",
        pregunta: "¿Qué es un sistema de gestión de base de datos orientada a objetos (ODBMS)?",
        opciones: [
          "Un sistema que solo almacena objetos físicos",
          "Un sistema que representa la información en forma de objetos, como en la programación orientada a objetos",
          "Un sistema que utiliza exclusivamente SQL para manejar datos",
          "Un sistema que solo trabaja con bases de datos relacionales",
        ],
        correcta: 1,
        preguntaId: "2050601001",
      },
      {
        id: "2050601002",
        pregunta: "En una BDOO, ¿qué es equivalente a una tabla en una base de datos relacional?",
        opciones: ["Un registro", "Un objeto", "Una clase", "Un atributo"],
        correcta: 2,
        preguntaId: "2050601002",
      },
      {
        id: "2050601003",
        pregunta: "¿Cuál de las siguientes NO es una característica mandatoria de las BDOO?",
        opciones: ["Soporte para objetos complejos", "Encapsulación", "Herencia múltiple", "Persistencia"],
        correcta: 2,
        preguntaId: "2050601003",
      },
      {
        id: "2050601004",
        pregunta:
          "¿Qué propiedad de las BDOO permite que una operación pueda aplicarse a objetos de distinta tipología?",
        opciones: ["Encapsulación", "Herencia", "Polimorfismo", "Persistencia"],
        correcta: 2,
        preguntaId: "2050601004",
      },
      {
        id: "2050601005",
        pregunta: "¿Cuál es una ventaja de las bases de datos orientadas a objetos?",
        opciones: [
          "Siempre son más rápidas que las bases de datos relacionales",
          "Utilizan SQL como lenguaje principal",
          "Permiten manipular conjuntos de datos complejos de manera más rápida",
          "Tienen una amplia documentación y estandarización",
        ],
        correcta: 2,
        preguntaId: "2050601005",
      },
      {
        id: "2050601006",
        pregunta:
          "¿Qué tipo de diagrama muestra los posibles estados en los que pueden estar un objeto y las transacciones que pueden realizar?",
        opciones: ["Diagrama de clases", "Diagrama de objetos", "Diagrama de secuencias", "Diagrama de estado"],
        correcta: 3,
        preguntaId: "2050601006",
      },
      {
        id: "2050601007",
        pregunta: "En las BDOO, ¿cómo se manejan las relaciones entre objetos?",
        opciones: [
          "Mediante tablas de relación",
          "A través de punteros",
          "Utilizando claves foráneas",
          "No se pueden establecer relaciones entre objetos",
        ],
        correcta: 2,
        preguntaId: "2050601007",
      },
      {
        id: "2050601008",
        pregunta: "¿Qué característica de las BDOO permite ocultar los detalles internos de un objeto?",
        opciones: ["Polimorfismo", "Herencia", "Encapsulación", "Persistencia"],
        correcta: 2,
        preguntaId: "2050601008",
      },
      {
        id: "2050601009",
        pregunta: "¿Cuál es una desventaja de las bases de datos orientadas a objetos?",
        opciones: [
          "No pueden manejar grandes volúmenes de datos",
          "Son más lentas que las bases de datos relacionales",
          "El uso de las BDOO está poco extendido y hay poca estandarización",
          "No soportan transacciones ACID",
        ],
        correcta: 2,
        preguntaId: "2050601009",
      },
      {
        id: "2050601010",
        pregunta: "¿Qué grupo es responsable de proporcionar estándares sobre bases de datos orientadas a objetos?",
        opciones: ["SQL", "ODMG", "ANSI", "ISO"],
        correcta: 1,
        preguntaId: "2050601010",
      },
      {
        id: "2050601011",
        pregunta:
          "¿Qué característica de las BDOO permite que los objetos hereden comportamientos dentro de una jerarquía de clases?",
        opciones: ["Encapsulación", "Polimorfismo", "Herencia", "Abstracción"],
        correcta: 2,
        preguntaId: "2050601011",
      },
      {
        id: "2050601012",
        pregunta: "En una BDOO, ¿cómo se realiza generalmente la recuperación de objetos?",
        opciones: [
          "Mediante consultas SQL",
          "A través de joins complejos",
          "Siguiendo punteros directamente",
          "Utilizando índices B-tree",
        ],
        correcta: 2,
        preguntaId: "2050601012",
      },
      {
        id: "2050601013",
        pregunta: "¿Qué ventaja ofrecen las BDOO en el manejo de datos multimedia?",
        opciones: [
          "No pueden manejar datos multimedia",
          "Requieren conversión a formatos especiales",
          "Los métodos de clase asociados con los datos son responsables de su correcta interpretación",
          "Siempre comprimen automáticamente los datos multimedia",
        ],
        correcta: 2,
        preguntaId: "2050601013",
      },
      {
        id: "2050601014",
        pregunta: "¿Qué característica de las BDOO permite ver un objeto como un conjunto de todas sus versiones?",
        opciones: ["Versionado de objetos", "Herencia múltiple", "Polimorfismo", "Encapsulación"],
        correcta: 0,
        preguntaId: "2050601014",
      },
      {
        id: "2050601015",
        pregunta: "¿Qué lenguaje utilizan principalmente las BDOO para realizar operaciones en la base de datos?",
        opciones: ["SQL", "XML", "Lenguajes de programación orientados a objetos", "JSON"],
        correcta: 2,
        preguntaId: "2050601015",
      },
    ],
    minimoParaAprobar: 12,
  },
  "2050701000e": {
    preguntas: [
      {
        id: "2050701001",
        pregunta: "¿Cuál de las siguientes NO es una característica típica de las bases de datos NoSQL?",
        opciones: [
          "No usan SQL como lenguaje principal de consultas",
          "Los datos almacenados no requieren estructuras fijas como tablas",
          "Garantizan completamente ACID (atomicidad, consistencia, aislamiento y durabilidad)",
          "Habitualmente escalan bien horizontalmente",
        ],
        correcta: 2,
        preguntaId: "2050701001",
      },
      {
        id: "2050701002",
        pregunta: "¿Cuáles son las tres tendencias principales que impulsan la adopción de tecnología NoSQL?",
        opciones: [
          "Computación en la nube, gran cantidad de usuarios y big data",
          "Inteligencia artificial, Internet de las cosas y blockchain",
          "Realidad virtual, 5G y edge computing",
          "Ciberseguridad, machine learning y computación cuántica",
        ],
        correcta: 0,
        preguntaId: "2050701002",
      },
      {
        id: "2050701003",
        pregunta: "¿Cuál de las siguientes NO es una ventaja de las bases de datos NoSQL?",
        opciones: [
          "Pueden manejar enormes cantidades de datos",
          "Escalamiento sencillo",
          "Se ejecutan en clusters de máquinas baratas",
          "Garantizan completamente las propiedades ACID",
        ],
        correcta: 3,
        preguntaId: "2050701003",
      },
      {
        id: "2050701004",
        pregunta: "¿Cuál es una desventaja común de las bases de datos NoSQL?",
        opciones: [
          "No pueden manejar grandes volúmenes de datos",
          "Falta de experiencia y escasez de desarrolladores con conocimientos en NoSQL",
          "No permiten escalabilidad horizontal",
          "Siempre requieren hardware muy costoso",
        ],
        correcta: 1,
        preguntaId: "2050701004",
      },
      {
        id: "2050701005",
        pregunta: "¿Cuáles son los cuatro tipos principales de bases de datos NoSQL?",
        opciones: [
          "Relacionales, jerárquicas, de red y orientadas a objetos",
          "Clave/Valor, basadas en columnas, basadas en documentos y basadas en grafos",
          "SQL, XML, JSON y YAML",
          "Transaccionales, analíticas, operacionales y de tiempo real",
        ],
        correcta: 1,
        preguntaId: "2050701005",
      },
      {
        id: "2050701006",
        pregunta: "¿Qué tipo de base de datos NoSQL es Apache HBase?",
        opciones: ["Basada en clave/valor", "Basada en documentos", "Basada en columnas", "Basada en grafos"],
        correcta: 2,
        preguntaId: "2050701006",
      },
      {
        id: "2050701007",
        pregunta: "¿Cuál es una característica distintiva de Cassandra?",
        opciones: [
          "Utiliza exclusivamente SQL para consultas",
          "Solo funciona con datos estructurados",
          "Proporciona una mezcla híbrida de un almacén de clave/valor con una base de datos orientada a columnas",
          "No es escalable",
        ],
        correcta: 2,
        preguntaId: "2050701007",
      },
      {
        id: "2050701008",
        pregunta: "¿Qué formato de datos utiliza principalmente CouchDB?",
        opciones: ["XML", "CSV", "JSON", "YAML"],
        correcta: 2,
        preguntaId: "2050701008",
      },
      {
        id: "2050701009",
        pregunta: "¿Cuál es una ventaja clave de MongoDB?",
        opciones: [
          "Utiliza SQL como lenguaje principal de consultas",
          "No permite el almacenamiento de documentos complejos",
          "Requiere un esquema fijo y predefinido",
          "Permite matrices y documentos integrados, reduciendo la necesidad de JOINs costosos",
        ],
        correcta: 3,
        preguntaId: "2050701009",
      },
      {
        id: "2050701010",
        pregunta: "¿Qué tipo de base de datos NoSQL es especialmente adecuada para datos altamente interconectados?",
        opciones: [
          "Bases de datos clave/valor",
          "Bases de datos basadas en columnas",
          "Bases de datos basadas en documentos",
          "Bases de datos basadas en grafos",
        ],
        correcta: 3,
        preguntaId: "2050701010",
      },
      {
        id: "2050701011",
        pregunta: "¿Cuál es una característica distintiva de Neo4j?",
        opciones: [
          "Utiliza tablas para almacenar datos",
          "No permite relaciones entre datos",
          "Almacena las relaciones entre objetos mediante una estructura de grafos",
          "Solo funciona con datos no estructurados",
        ],
        correcta: 2,
        preguntaId: "2050701011",
      },
      {
        id: "2050701012",
        pregunta: "¿Qué tipo de base de datos NoSQL es Redis?",
        opciones: ["Basada en documentos", "Basada en grafos", "Basada en columnas", "Basada en clave/valor"],
        correcta: 3,
        preguntaId: "2050701012",
      },
      {
        id: "2050701013",
        pregunta: "¿Cuál es una característica principal de Riak?",
        opciones: [
          "Solo funciona con datos estructurados",
          "No es escalable",
          "Ofrece almacenamiento en la nube a cualquier escala en nubes públicas y privadas",
          "Utiliza exclusivamente SQL para consultas",
        ],
        correcta: 2,
        preguntaId: "2050701013",
      },
      {
        id: "2050701014",
        pregunta: "¿Qué problema potencial enfrentan las bases de datos NoSQL en términos de compatibilidad?",
        opciones: [
          "Todas las bases de datos NoSQL son totalmente compatibles entre sí",
          "Las bases de datos NoSQL tienen pocos estándares en común, lo que dificulta cambiar de un proveedor a otro",
          "Solo son compatibles con sistemas operativos específicos",
          "No pueden interactuar con bases de datos relacionales bajo ninguna circunstancia",
        ],
        correcta: 1,
        preguntaId: "2050701014",
      },
      {
        id: "2050701015",
        pregunta: "¿Qué significa el término 'no solo SQL' en el contexto de NoSQL?",
        opciones: [
          "Que las bases de datos NoSQL nunca usan SQL",
          "Que las bases de datos NoSQL son superiores a las bases de datos SQL",
          "Que algunas bases de datos NoSQL pueden soportar lenguajes de consulta tipo SQL además de sus propias interfaces",
          "Que NoSQL es un reemplazo completo para SQL",
        ],
        correcta: 2,
        preguntaId: "2050701015",
      },
    ],
    minimoParaAprobar: 12,
  },
 



}

