export const preguntas = {
    "2010101000e": {
      preguntas: [
        {
          id: "2010101001",
          pregunta: "¿Qué es un bit?",
          opciones: [
            "Una unidad de almacenamiento de 8 dígitos binarios",
            "La unidad mínima de información que puede tomar el valor 0 o 1",
            "Un sistema de numeración de base 10",
            "Un tipo de operador lógico",
          ],
          correcta: 1,
          explicacionId: "2010101001",
        },
        {
          id: "2010101002",
          pregunta: "¿Qué es un operador binario?",
          opciones: [
            "Un sistema de numeración de base 2",
            "Una unidad de almacenamiento de información",
            "Un operador que permite transformar y unir valores binarios",
            "Un tipo de codificación de caracteres",
          ],
          correcta: 2,
          explicacionId: "2010101002",
        },
        {
          id: "2010101003",
          pregunta: "¿Qué es el sistema BCD?",
          opciones: [
            "Un sistema de codificación que usa 8 bits por carácter",
            "Un operador lógico binario",
            "Un sistema de codificación que usa 4 bits para representar cada dígito decimal",
            "Un estándar de codificación Unicode",
          ],
          correcta: 2,
          explicacionId: "2010101003",
        },
        {
          id: "2010101004",
          pregunta: "¿Qué es un byte?",
          opciones: [
            "Una unidad de información compuesta por 4 bits",
            "Un sistema de numeración de base 16",
            "Una unidad de información compuesta por 8 bits",
            "Un operador lógico binario",
          ],
          correcta: 2,
          explicacionId: "2010101004",
        },
        {
          id: "2010101005",
          pregunta: "¿Cuál de los siguientes NO es un sistema de codificación de caracteres?",
          opciones: ["ASCII", "Unicode", "EBCDIC", "BCD"],
          correcta: 3,
          explicacionId: "2010101005",
        },
        {
          id: "2010101006",
          pregunta: "¿Qué base utiliza el sistema de numeración hexadecimal?",
          opciones: ["Base 2", "Base 8", "Base 10", "Base 16"],
          correcta: 3,
          explicacionId: "2010101006",
        },
        {
          id: "2010101007",
          pregunta: "¿Cuántos dígitos utiliza el sistema de numeración octal?",
          opciones: ["2 dígitos (0-1)", "8 dígitos (0-7)", "10 dígitos (0-9)", "16 dígitos (0-9 y A-F)"],
          correcta: 1,
          explicacionId: "2010101007",
        },
        {
          id: "2010101008",
          pregunta:
            "¿Qué característica tienen en común los sistemas de numeración binario, decimal, hexadecimal y octal?",
          opciones: [
            "Todos usan el mismo número de dígitos",
            "Todos son sistemas posicionales",
            "Todos usan letras y números",
            "Todos tienen la misma base",
          ],
          correcta: 1,
          explicacionId: "2010101008",
        },
        {
          id: "2010101009",
          pregunta: "¿Cuántos bytes equivalen a 1 Kilobyte (KB) según el Sistema Internacional?",
          opciones: ["1000 bytes", "1024 bytes", "100 bytes", "10000 bytes"],
          correcta: 0,
          explicacionId: "2010101009",
        },
        {
          id: "2010101010",
          pregunta: "¿En qué unidad se mide comúnmente la transferencia de información en redes de comunicaciones?",
          opciones: [
            "Bytes por segundo (B/s)",
            "Bits por segundo (bps)",
            "Caracteres por segundo (cps)",
            "Megabytes por segundo (MB/s)",
          ],
          correcta: 1,
          explicacionId: "2010101010",
        },
      ],
      minimoParaAprobar: 7,
    },
    "2010102000e": {
        preguntas: [
          {
            id: "2010102001",
            pregunta: "¿Qué es un sistema de información?",
            opciones: [
              "Un conjunto de elementos que interactúan entre sí para conseguir un fin común",
              "Un conjunto de hardware y software",
              "Una red de comunicaciones entre equipos",
              "Un grupo de personas que manejan datos",
            ],
            correcta: 0,
            explicacionId: "2010102001",
          },
          {
            id: "2010102002",
            pregunta: "¿Qué se considera parte del hardware en un sistema de información?",
            opciones: [
              "Los programas de aplicación",
              "Los equipos informáticos y sus periféricos",
              "Las bases de datos",
              "Los procedimientos operativos",
            ],
            correcta: 1,
            explicacionId: "2010102002",
          },
          {
            id: "2010102003",
            pregunta: "¿Qué es el software en un sistema de información?",
            opciones: [
              "La infraestructura física del sistema",
              "Los usuarios del sistema",
              "La parte lógica del sistema que se ejecuta en el mismo",
              "Los datos procesados por el sistema",
            ],
            correcta: 2,
            explicacionId: "2010102003",
          },
          {
            id: "2010102004",
            pregunta: "¿Qué elemento del sistema de información se refiere a la interconexión entre sistemas?",
            opciones: ["Hardware", "Software", "Comunicaciones", "Procedimientos"],
            correcta: 2,
            explicacionId: "2010102004",
          },
          {
            id: "2010102005",
            pregunta: "En un sistema de información, ¿qué se considera como 'datos'?",
            opciones: [
              "Los equipos informáticos",
              "Los programas de aplicación",
              "La información a procesar o los resultados obtenidos",
              "Los usuarios del sistema",
            ],
            correcta: 2,
            explicacionId: "2010102005",
          },
          {
            id: "2010102006",
            pregunta: "¿Quiénes se consideran 'personas' en un sistema de información?",
            opciones: [
              "Solo los administradores del sistema",
              "Solo los operadores del sistema",
              "Los equipos y periféricos",
              "Todos los usuarios que se relacionan con el sistema",
            ],
            correcta: 3,
            explicacionId: "2010102006",
          },
          {
            id: "2010102007",
            pregunta: "¿Qué son los procedimientos o directivas en un sistema de información?",
            opciones: [
              "Los componentes físicos del sistema",
              "El código que se ejecuta en el sistema",
              "Pautas repetitivas para el gobierno del sistema",
              "Los datos procesados por el sistema",
            ],
            correcta: 2,
            explicacionId: "2010102007",
          },
        ],
        minimoParaAprobar: 5,
      },
      "2010103000e": {
        preguntas: [
          {
            id: "2010103001",
            pregunta:
              "¿Qué característica de un sistema de información se refiere a que la información almacenada debe ser importante?",
            opciones: ["Persistencia", "Relevancia", "Integración", "Control"],
            correcta: 1,
            explicacionId: "2010103001",
          },
          {
            id: "2010103002",
            pregunta: "¿Qué característica permite que la información permanezca en el sistema de forma indefinida?",
            opciones: ["Relevancia", "Persistencia", "Flujo de información", "Integración"],
            correcta: 1,
            explicacionId: "2010103002",
          },
          {
            id: "2010103003",
            pregunta:
              "¿Qué característica se refiere a que los componentes del sistema comparten información de manera ordenada?",
            opciones: ["Control", "Flujo de información", "Integración", "Persistencia"],
            correcta: 2,
            explicacionId: "2010103003",
          },
          {
            id: "2010103004",
            pregunta: "¿Qué característica indica que el sistema sigue un orden predeterminado en sus funciones?",
            opciones: ["Flujo de información", "Control", "Relevancia", "Integración"],
            correcta: 0,
            explicacionId: "2010103004",
          },
          {
            id: "2010103005",
            pregunta: "¿Qué característica se refiere al procesamiento lógico de entradas para determinar salidas?",
            opciones: ["Persistencia", "Integración", "Control", "Relevancia"],
            correcta: 2,
            explicacionId: "2010103005",
          },
          {
            id: "2010103006",
            pregunta: "¿Qué función del sistema de información se encarga de capturar datos en bruto?",
            opciones: ["Almacenamiento", "Procesamiento", "Distribución", "Recopilación"],
            correcta: 3,
            explicacionId: "2010103006",
          },
          {
            id: "2010103007",
            pregunta: "¿Qué función guarda de forma estructurada la información recopilada?",
            opciones: ["Recopilación", "Almacenamiento", "Procesamiento", "Distribución"],
            correcta: 1,
            explicacionId: "2010103007",
          },
          {
            id: "2010103008",
            pregunta: "¿Qué función convierte una entrada de datos en una salida mediante instrucciones?",
            opciones: ["Recopilación", "Almacenamiento", "Procesamiento", "Distribución"],
            correcta: 2,
            explicacionId: "2010103008",
          },
          {
            id: "2010103009",
            pregunta: "¿Qué función transfiere la información procesada a las personas o a otros sistemas?",
            opciones: ["Recopilación", "Almacenamiento", "Procesamiento", "Distribución"],
            correcta: 3,
            explicacionId: "2010103009",
          },
        ],
        minimoParaAprobar: 7,
      },
      "2010104000e": {
        preguntas: [
          {
            id: "2010104001",
            pregunta:
              "¿Qué tipo de sistema de información surge al adaptar los ordenadores al tratamiento de datos de una organización?",
            opciones: [
              "Sistemas de procesamiento de transacciones (TPS)",
              "Sistemas de información gerencial (MIS)",
              "Sistemas de procesamiento electrónico de datos (EDPS)",
              "Sistemas de apoyo a las decisiones (DSS)",
            ],
            correcta: 2,
            explicacionId: "2010104001",
          },
          {
            id: "2010104002",
            pregunta:
              "¿Qué sistemas surgen en la década de los 60 para automatizar específicamente los procesos de compra y venta?",
            opciones: [
              "Sistemas de procesamiento de transacciones (TPS)",
              "Sistemas de información gerencial (MIS)",
              "Sistemas de procesamiento electrónico de datos (EDPS)",
              "Sistemas de apoyo a las decisiones (DSS)",
            ],
            correcta: 0,
            explicacionId: "2010104002",
          },
          {
            id: "2010104003",
            pregunta: "¿Qué sistemas generan informes estadísticos sobre las operaciones de la organización?",
            opciones: [
              "Sistemas de procesamiento de transacciones (TPS)",
              "Sistemas de información gerencial (MIS)",
              "Sistemas de procesamiento electrónico de datos (EDPS)",
              "Sistemas de apoyo a las decisiones (DSS)",
            ],
            correcta: 1,
            explicacionId: "2010104003",
          },
          {
            id: "2010104004",
            pregunta:
              "¿Qué sistemas utilizan el conocimiento almacenado y la información en tiempo real para ayudar en la toma de decisiones estratégicas?",
            opciones: [
              "Sistemas de procesamiento de transacciones (TPS)",
              "Sistemas de información gerencial (MIS)",
              "Sistemas de apoyo a las decisiones (DSS)",
              "Sistema de información para ejecutivos (EIS)",
            ],
            correcta: 2,
            explicacionId: "2010104004",
          },
          {
            id: "2010104005",
            pregunta:
              "¿Qué sistemas evolucionaron de los DSS en la década de los 80 y coinciden con la expansión de los equipos personales en las oficinas?",
            opciones: [
              "Sistemas de automatización de oficinas (OAS)",
              "Sistema de información para ejecutivos (EIS)",
              "Sistemas de planificación de recursos (ERP)",
              "Sistemas Expertos (SE)",
            ],
            correcta: 1,
            explicacionId: "2010104005",
          },
          {
            id: "2010104006",
            pregunta: "¿Qué sistemas surgen para facilitar las tareas administrativas en oficinas?",
            opciones: [
              "Sistemas de automatización de oficinas (OAS)",
              "Sistema de información para ejecutivos (EIS)",
              "Sistemas de planificación de recursos (ERP)",
              "Sistemas Expertos (SE)",
            ],
            correcta: 0,
            explicacionId: "2010104006",
          },
          {
            id: "2010104007",
            pregunta:
              "¿Qué sistemas surgen en los años 90 para gestionar la información y los procesos de toda una administración?",
            opciones: [
              "Sistemas de automatización de oficinas (OAS)",
              "Sistema de información para ejecutivos (EIS)",
              "Sistemas de planificación de recursos (ERP)",
              "Sistemas Expertos (SE)",
            ],
            correcta: 2,
            explicacionId: "2010104007",
          },
          {
            id: "2010104008",
            pregunta: "¿Qué sistemas pretenden simular el razonamiento humano de un experto en un área de especialización?",
            opciones: [
              "Sistemas de automatización de oficinas (OAS)",
              "Sistema de información para ejecutivos (EIS)",
              "Sistemas de planificación de recursos (ERP)",
              "Sistemas Expertos (SE)",
            ],
            correcta: 3,
            explicacionId: "2010104008",
          },
          {
            id: "2010104008",
            pregunta: "¿Cuál de los siguientes NO es un tipo de Sistema Experto?",
            opciones: [
              "Basados en reglas (RBR)",
              "Basados en casos (CBR)",
              "Basados en redes bayesianas",
              "Basados en procesamiento de transacciones (TPS)",
            ],
            correcta: 3,
            explicacionId: "2010104009",
          },
        ],
        minimoParaAprobar: 7,
      },
      "2010201000e": {
    preguntas: [
      {
        explicacionId: "2010201001",
        pregunta: "¿Quién describió la arquitectura que se considera la base de los ordenadores modernos?",
        opciones: ["Alan Turing", "John von Neumann", "Charles Babbage", "Ada Lovelace"],
        correcta: 1,
        id: "2010201001",
      },
      {
        explicacionId: "2010201002",
        pregunta: "¿Qué componentes incluye la unidad de procesamiento (CPU) en la arquitectura von Neumann?",
        opciones: [
          "Unidad aritmético lógica, unidad de control y registros",
          "Memoria principal, unidad de control y registros",
          "Unidad aritmético lógica, memoria caché y bus de datos",
          "Unidad de control, bus de direcciones y memoria principal",
        ],
        correcta: 0,
        id: "2010201001",
      },
      {
        explicacionId: "2010201003",
        pregunta: "¿Cuál es una característica principal de la arquitectura Von Neumann?",
        opciones: [
          "Memorias separadas para instrucciones y datos",
          "Ejecución paralela de instrucciones",
          "Programas almacenados en la memoria principal",
          "Ausencia de instrucciones de salto",
        ],
        correcta: 2,
        id: "2010201002",
      },
      {
        explicacionId: "2010201004",
        pregunta: "¿Qué se conoce como 'cuello de botella Von Neumann'?",
        opciones: [
          "La limitación en la velocidad de la CPU",
          "La existencia de un bus común para datos e instrucciones",
          "La necesidad de instrucciones de salto",
          "La ejecución secuencial de instrucciones",
        ],
        correcta: 1,
        id: "2010201002",
      },
      {
        explicacionId: "2010201005",
        pregunta: "¿Cuál es la principal diferencia entre la arquitectura Harvard y la arquitectura von Neumann?",
        opciones: [
          "La arquitectura Harvard no utiliza CPU",
          "La arquitectura Harvard usa memorias separadas para instrucciones y datos",
          "La arquitectura Harvard solo ejecuta una instrucción a la vez",
          "La arquitectura Harvard no permite el acceso simultáneo a instrucciones y datos",
        ],
        correcta: 1,
        id: "2010201003",
      },
      {
        id: "2010201003",
        pregunta: "¿Qué ventaja ofrece la arquitectura Harvard sobre la arquitectura von Neumann?",
        opciones: [
          "Mayor capacidad de almacenamiento",
          "Menor consumo de energía",
          "Posibilidad de leer una instrucción y acceder a datos simultáneamente",
          "Simplificación del diseño del procesador",
        ],
        correcta: 2,
        explicacionId: "2010201006",
      },
      {
        id: "2010201004",
        pregunta: "¿Qué característica tiene la arquitectura de caché dividida en la arquitectura Harvard modificada?",
        opciones: [
          "Utiliza una única caché para instrucciones y datos",
          "Tiene cachés separadas de instrucciones y datos con el mismo espacio de direcciones",
          "Elimina completamente el uso de caché",
          "Utiliza la memoria principal como caché",
        ],
        correcta: 1,
        explicacionId: "2010201007",
      },
      {
        id: "2010201004",
        pregunta:
          "En la arquitectura Harvard modificada, ¿qué permite la 'arquitectura de memoria de instrucciones como los datos'?",
        opciones: [
          "Eliminar la separación entre memoria de instrucciones y datos",
          "Acceder al contenido de la memoria de instrucciones como si fueran datos",
          "Aumentar la velocidad de acceso a la memoria",
          "Reducir el tamaño total de la memoria",
        ],
        correcta: 1,
        explicacionId: "2010201008",
      },
      {
        id: "2010201005",
        pregunta: "¿En qué se basa la taxonomía de Flynn?",
        opciones: [
          "En el tamaño de la memoria",
          "En la velocidad del procesador",
          "En el número de instrucciones concurrentes y flujos de datos",
          "En el tipo de arquitectura de caché",
        ],
        correcta: 2,
        explicacionId: "2010201009",
      },
      {
        id: "2010201005",
        pregunta: "¿Qué significa SIMD en la taxonomía de Flynn?",
        opciones: [
          "Sistema Integrado de Múltiples Datos",
          "Secuencia de Instrucciones Múltiples Datos",
          "Una Instrucción, Múltiples Datos",
          "Sistema de Instrucciones para Manejo de Datos",
        ],
        correcta: 2,
        explicacionId: "2010201010",
      },
      {
        id: "2010201005",
        pregunta: "¿Cuál de las siguientes arquitecturas de Flynn es considerada poco común?",
        opciones: ["SISD", "SIMD", "MISD", "MIMD"],
        correcta: 2,
        explicacionId: "2010201011",
      },
      {
        id: "2010201005",
        pregunta: "¿Qué tipo de arquitectura según Flynn utilizan típicamente los sistemas distribuidos?",
        opciones: ["SISD", "SIMD", "MISD", "MIMD"],
        correcta: 3,
        explicacionId: "2010201012",
      },
      {
        id: "2010201005",
        pregunta: "¿Qué arquitectura de Flynn corresponde a la Arquitectura Von-Neumann tradicional?",
        opciones: ["SISD", "SIMD", "MISD", "MIMD"],
        correcta: 0,
        explicacionId: "2010201013",
      },
      {
        id: "2010201006",
        pregunta: "¿Quién realizó una nueva clasificación ampliando la arquitectura MIMD de Flynn?",
        opciones: ["John von Neumann", "Michael J. Flynn", "Andrew S. Tanenbaum", "Gordon Moore"],
        correcta: 2,
        explicacionId: "2010201014",
      },
      {
        id: "2010201006",
        pregunta: "¿Qué significa UMA en la clasificación de Tanenbaum?",
        opciones: [
          "Unified Memory Access",
          "Uniform Memory Access",
          "Unequal Memory Access",
          "Unique Memory Architecture",
        ],
        correcta: 1,
        explicacionId: "2010201015",
      },
      {
        id: "2010201006",
        pregunta: "En la clasificación de Tanenbaum, ¿qué tipo de arquitectura utiliza solo memoria caché?",
        opciones: ["UMA", "NUMA", "COMA", "MPP"],
        correcta: 2,
        explicacionId: "2010201016",
      },
      {
        id: "2010201006",
        pregunta: "¿Qué significa COW en el contexto de la clasificación de Tanenbaum?",
        opciones: [
          "Computer On Wheels",
          "Cluster Of Workstations",
          "Centralized Operating Workload",
          "Coordinated Output Workers",
        ],
        correcta: 1,
        explicacionId: "2010201017",
      },
      {
        id: "2010201006",
        pregunta:
          "¿Qué tipo de sistemas se clasifican como 'múltiples computadores ligeramente acoplados' según Tanenbaum?",
        opciones: [
          "Sistemas UMA",
          "Sistemas NUMA",
          "Sistemas COMA",
          "Clusters y sistemas de multiprocesamiento masivo (MPP)",
        ],
        correcta: 3,
        explicacionId: "2010201018",
      },
    ],
    minimoParaAprobar: 13,
  },
  "2010301000e": {
    preguntas: [
      {
        id: "2010301001",
        pregunta: "¿Qué es la placa base?",
        opciones: [
          "Un dispositivo de almacenamiento",
          "Una tarjeta de circuito impreso donde se conectan los componentes del equipo microinformático",
          "Un tipo de memoria RAM",
          "El procesador principal del ordenador",
        ],
        correcta: 1,
        explicacionId: "2010301001",
      },
      {
        id: "2010301002",
        pregunta: "¿Qué función cumplen los conectores de alimentación en la placa base?",
        opciones: [
          "Conectar dispositivos externos",
          "Regular la velocidad de la CPU",
          "Proporcionar diferentes voltajes e intensidades necesarios para el funcionamiento",
          "Almacenar información de configuración",
        ],
        correcta: 2,
        explicacionId: "2010301002",
      },
      {
        id: "2010301003",
        pregunta: "¿Qué es el zócalo de CPU?",
        opciones: [
          "Un tipo de memoria",
          "El reloj del sistema",
          "Un receptáculo que encastra el procesador y lo conecta al resto de componentes",
          "Un conector de alimentación",
        ],
        correcta: 2,
        explicacionId: "2010301003",
      },
      {
        id: "2010301004",
        pregunta: "¿Qué es el Front Side Bus (FSB)?",
        opciones: [
          "Un tipo de memoria RAM",
          "El bus de datos que comunica la CPU con el northbridge del chipset",
          "Un conector de alimentación",
          "El reloj del sistema",
        ],
        correcta: 1,
        explicacionId: "2010301004",
      },
      {
        id: "2010301005",
        pregunta: "¿Qué son las ranuras o slots de memoria RAM?",
        opciones: [
          "Conectores de alimentación",
          "Puertos para añadir tarjetas de expansión",
          "Receptáculos para insertar los módulos de memoria RAM",
          "Conectores para dispositivos externos",
        ],
        correcta: 2,
        explicacionId: "2010301005",
      },
      {
        id: "2010301006",
        pregunta: "¿Qué función cumple el chipset en la placa base?",
        opciones: [
          "Regular la velocidad de la CPU",
          "Almacenar información de configuración",
          "Servir de puente de comunicación con el resto de componentes",
          "Proporcionar alimentación eléctrica",
        ],
        correcta: 2,
        explicacionId: "2010301006",
      },
      {
        id: "2010301007",
        pregunta: "¿Cuál es la función del reloj en la placa base?",
        opciones: [
          "Almacenar la fecha y hora",
          "Regular la velocidad de ejecución de la CPU",
          "Conectar dispositivos externos",
          "Gestionar la interconexión entre periféricos",
        ],
        correcta: 1,
        explicacionId: "2010301007",
      },
      {
        id: "2010301008",
        pregunta: "¿Qué información preserva la RAM CMOS?",
        opciones: [
          "Los programas en ejecución",
          "Los datos del disco duro",
          "La configuración del equipo, la fecha y la hora",
          "Las instrucciones de la CPU",
        ],
        correcta: 2,
        explicacionId: "2010301008",
      },
      {
        id: "2010301009",
        pregunta: "¿Qué conecta el bus de memoria?",
        opciones: [
          "La CPU con los dispositivos de almacenamiento",
          "El chipset con la memoria temporal",
          "Los conectores de entrada/salida con la CPU",
          "Las ranuras de expansión con el chipset",
        ],
        correcta: 1,
        explicacionId: "2010301009",
      },
      {
        id: "2010301010",
        pregunta: "¿Qué función cumple el bus de expansión o bus E/S?",
        opciones: [
          "Conectar la memoria RAM con la CPU",
          "Unir la CPU a los conectores de entrada/salida y las ranuras de expansión",
          "Regular la velocidad de la CPU",
          "Almacenar información de configuración",
        ],
        correcta: 1,
        explicacionId: "2010301010",
      },
      {
        id: "2010301011",
        pregunta: "¿Qué norma suelen cumplir los conectores de entrada/salida en la placa base?",
        opciones: ["USB 3.0", "IEEE 1394", "PC99", "SATA III"],
        correcta: 2,
        explicacionId: "2010301011",
      },
      {
        id: "2010301012",
        pregunta: "¿Qué son las ranuras de expansión en la placa base?",
        opciones: [
          "Conectores de alimentación",
          "Puertos para añadir circuitos integrados de gestión de vídeo, sonido o comunicaciones",
          "Slots para insertar módulos de memoria RAM",
          "Conectores para el procesador",
        ],
        correcta: 1,
        explicacionId: "2010301012",
      },
    ],
    minimoParaAprobar: 7,
  },
  "2010302000e": {
    preguntas: [
      {
        id: "2010302001",
        pregunta: "¿Cuál es la función principal de la Unidad Central de Procesamiento (CPU)?",
        opciones: [
          "Almacenar datos permanentemente",
          "Interpretar instrucciones y procesar datos",
          "Controlar los dispositivos de entrada/salida",
          "Gestionar la red de comunicaciones",
        ],
        correcta: 1,
        explicacionId: "2010302001",
      },
      {
        id: "2010302002",
        pregunta: "¿Cuál de las siguientes NO es una característica que diferencia a una CPU de otra?",
        opciones: [
          "Frecuencia de reloj",
          "Número de núcleos",
          "Capacidad de memoria cache",
          "Tamaño físico del procesador",
        ],
        correcta: 3,
        explicacionId: "2010302002",
      },
      {
        id: "2010302003",
        pregunta: "¿Cuál de los siguientes NO es un componente principal de la CPU?",
        opciones: ["Unidad de control (UC)", "Unidad aritmético lógica (UAL)", "Memoria RAM", "Conjunto de Registros"],
        correcta: 2,
        explicacionId: "2010302003",
      },
      {
        id: "2010302004",
        pregunta: "¿Cuál es la principal diferencia entre las arquitecturas RISC y CISC?",
        opciones: [
          "RISC usa instrucciones complejas mientras que CISC usa instrucciones simples",
          "RISC tiene un conjunto reducido de instrucciones simples, mientras que CISC tiene un conjunto amplio de instrucciones complejas",
          "RISC solo se usa en supercomputadoras, mientras que CISC se usa en computadoras personales",
          "No hay diferencia significativa entre RISC y CISC",
        ],
        correcta: 1,
        explicacionId: "2010302004",
      },
      {
        id: "2010302005",
        pregunta: "¿Cuál es el orden correcto de las fases del ciclo de una instrucción de la CPU?",
        opciones: [
          "Fetch, Execute, Decode, Store",
          "Decode, Fetch, Execute, Store",
          "Fetch, Decode, Execute, Store",
          "Execute, Fetch, Decode, Store",
        ],
        correcta: 2,
        explicacionId: "2010302005",
      },
      {
        id: "2010302006",
        pregunta: "¿En qué modo de direccionamiento el operando está incluido directamente en la instrucción?",
        opciones: ["Implícito", "Inmediato", "Directo", "Indirecto"],
        correcta: 1,
        explicacionId: "2010302006",
      },
      {
        id: "2010302007",
        pregunta: "¿Cuál es la principal diferencia entre multihilo y multiprocesamiento?",
        opciones: [
          "El multihilo solo funciona en CPUs de un solo núcleo, mientras que el multiprocesamiento requiere múltiples núcleos",
          "El multihilo divide un proceso en hilos que se ejecutan en una o varias CPUs, mientras que el multiprocesamiento ejecuta varios procesos simultáneamente en varios procesadores o núcleos",
          "El multihilo es una técnica de software, mientras que el multiprocesamiento es una característica de hardware",
          "No hay diferencia significativa entre multihilo y multiprocesamiento",
        ],
        correcta: 1,
        explicacionId: "2010302007",
      },
    ],
    minimoParaAprobar: 5,
  },
  "2010303000e": {
    preguntas: [
      {
        id: "2010303001",
        pregunta: "¿Cuál es la principal diferencia entre la memoria ROM y la memoria RAM?",
        opciones: [
          "La ROM es más rápida que la RAM",
          "La ROM es de sólo lectura y no volátil, mientras que la RAM permite lectura y escritura pero es volátil",
          "La ROM tiene mayor capacidad que la RAM",
          "La ROM se usa para almacenar el sistema operativo, mientras que la RAM se usa para la BIOS",
        ],
        correcta: 1,
        explicacionId: "2010303002",
      },
      {
        id: "2010303002",
        pregunta:
          "¿Cuál de los siguientes tipos de ROM permite ser borrada y regrabada múltiples veces usando electricidad?",
        opciones: ["Mask ROM", "PROM", "UV-EPROM", "EEPROM"],
        correcta: 3,
        explicacionId: "2010303002",
      },
      {
        id: "2010303003",
        pregunta: "¿Qué significa POST en el contexto de las rutinas de la memoria ROM?",
        opciones: ["Power On System Test", "Power On Self Test", "Program On System Test", "Program On Self Test"],
        correcta: 1,
        explicacionId: "2010303003",
      },
      {
        id: "2010303004",
        pregunta: "¿Cuál es la principal característica de la memoria RAM?",
        opciones: [
          "Es no volátil",
          "Solo puede ser leída por la CPU",
          "Permite el acceso directo a cualquiera de sus posiciones y puede ser leída y escrita",
          "Se usa para almacenar permanentemente el sistema operativo",
        ],
        correcta: 2,
        explicacionId: "2010303004",
      },
      {
        id: "2010303005",
        pregunta: "¿Cuál de los siguientes NO es un tipo de módulo de memoria RAM?",
        opciones: ["SIPP", "SIMM", "DIMM", "RISC"],
        correcta: 3,
        explicacionId: "2010303005",
      },
      {
        id: "2010303006",
        pregunta: "¿Cuál es la principal diferencia entre la RAM dinámica (DRAM) y la RAM estática (SRAM)?",
        opciones: [
          "La DRAM es más rápida que la SRAM",
          "La SRAM necesita un circuito de refresco, mientras que la DRAM no",
          "La DRAM está basada en condensadores, mientras que la SRAM usa celdas de transistores",
          "La DRAM es no volátil, mientras que la SRAM es volátil",
        ],
        correcta: 2,
        explicacionId: "2010303006",
      },
      {
        id: "2010303007",
        pregunta: "¿Cuál es la principal característica de la memoria CAM (Content-Addressable Memory)?",
        opciones: [
          "Es más lenta que la RAM en operaciones de búsqueda",
          "Busca un dato en toda la memoria en una sola operación",
          "Es más barata que la RAM",
          "Consume menos energía que la RAM",
        ],
        correcta: 1,
        explicacionId: "2010303007",
      },
      {
        id: "2010303008",
        pregunta: "¿Por qué las memorias CAM son más caras que las RAM?",
        opciones: [
          "Porque son más rápidas",
          "Porque son no volátiles",
          "Porque cada bit debe disponer de su propio circuito de comparación",
          "Porque tienen mayor capacidad de almacenamiento",
        ],
        correcta: 2,
        explicacionId: "2010303008",
      },
    ],
    minimoParaAprobar: 6,
  },
  "2010304000e": {
    preguntas: [
      {
        id: "2010304001",
        pregunta: "¿Cuál es la función principal de los sistemas de entrada y salida?",
        opciones: [
          "Procesar datos internamente en la CPU",
          "Almacenar datos permanentemente",
          "Permitir el intercambio de datos entre el sistema de información y el mundo exterior",
          "Generar informes del sistema",
        ],
        correcta: 2,
        explicacionId: "2010304001",
      },
      {
        id: "2010304002",
        pregunta: "¿Cuál de los siguientes NO es un tipo de dispositivo periférico mencionado en el texto?",
        opciones: [
          "Dispositivos de interfaz de usuarios",
          "Dispositivos de almacenamiento de datos",
          "Dispositivos de comunicación con otros procesadores",
          "Dispositivos de procesamiento paralelo",
        ],
        correcta: 3,
        explicacionId: "2010304001",
      },
      {
        id: "2010304003",
        pregunta: "¿Qué se considera como memoria secundaria?",
        opciones: [
          "La memoria RAM",
          "La memoria ROM",
          "Los dispositivos de almacenamiento de datos como discos magnéticos o de estado sólido",
          "La memoria caché",
        ],
        correcta: 2,
        explicacionId: "2010304001",
      },
      {
        id: "2010304004",
        pregunta: "¿Qué tipo de dispositivos permiten la comunicación a través de redes?",
        opciones: [
          "Dispositivos de interfaz de usuarios",
          "Dispositivos de almacenamiento de datos",
          "Dispositivos de comunicación con otros procesadores",
          "Dispositivos de adquisición de datos",
        ],
        correcta: 2,
        explicacionId: "2010304001",
      },
      {
        id: "2010304005",
        pregunta: "¿Qué característica comparten todos los dispositivos periféricos según el texto?",
        opciones: [
          "Tienen la misma velocidad de transferencia",
          "Usan el mismo formato de datos",
          "Son identificados de manera unívoca por la CPU",
          "Tienen la misma forma de funcionamiento",
        ],
        correcta: 2,
        explicacionId: "2010304002",
      },
      {
        id: "2010304006",
        pregunta: "¿Qué es un controlador o driver?",
        opciones: [
          "Un dispositivo de hardware que controla otros periféricos",
          "Un software específico que adapta las instrucciones para cada dispositivo",
          "Un módulo de entrada/salida común para todos los periféricos",
          "Un tipo de memoria que almacena instrucciones para los periféricos",
        ],
        correcta: 1,
        explicacionId: "2010304003",
      },
      {
        id: "2010304007",
        pregunta: "¿Cuál es la función principal de un controlador o driver?",
        opciones: [
          "Aumentar la velocidad de transferencia de datos",
          "Identificar unívocamente los dispositivos para la CPU",
          "Adaptar las instrucciones a las peculiaridades del dispositivo",
          "Sincronizar todos los dispositivos periféricos",
        ],
        correcta: 2,
        explicacionId: "2010304003",
      },
    ],
    minimoParaAprobar: 5,
  },
  "2010305000e": {
    preguntas: [
      {
        id: "2010305001",
        pregunta: "¿Cuál es la principal diferencia entre el bus de datos y el bus de direcciones?",
        opciones: [
          "El bus de datos es más rápido que el bus de direcciones",
          "El bus de datos intercambia información entre componentes, mientras que el bus de direcciones transfiere direcciones de memoria",
          "El bus de datos es paralelo y el bus de direcciones es serie",
          "El bus de datos es unidireccional y el bus de direcciones es bidireccional",
        ],
        correcta: 1,
        explicacionId: "2010305002",
      },
      {
        id: "2010305002",
        pregunta: "¿Qué característica define a un bus serie?",
        opciones: [
          "Transmite varios bits simultáneamente",
          "Utiliza múltiples cables para la transmisión",
          "Transfiere los datos bit a bit, normalmente por un único cable",
          "Es más rápido que un bus paralelo en todas las situaciones",
        ],
        correcta: 2,
        explicacionId: "2010305003",
      },
      {
        id: "2010305003",
        pregunta: "¿Cuál fue la principal ventaja del bus AGP sobre el bus PCI para tarjetas gráficas?",
        opciones: [
          "AGP era un bus serie mientras que PCI era paralelo",
          "AGP tenía un ancho de banda dedicado al no compartirse con otros dispositivos",
          "AGP podía transmitir datos en ambas direcciones simultáneamente",
          "AGP utilizaba voltajes más bajos, reduciendo el consumo de energía",
        ],
        correcta: 1,
        explicacionId: "2010305004",
      },
      {
        id: "2010305004",
        pregunta: "¿Qué característica distingue al bus PCIe de sus predecesores?",
        opciones: [
          "Es un bus paralelo de alta velocidad",
          "Utiliza tecnología de multiplexación por división de tiempo",
          "Está estructurado como carriles punto a punto, full-duplex, trabajando en serie",
          "Solo se utiliza para conectar dispositivos de almacenamiento",
        ],
        correcta: 2,
        explicacionId: "2010305004",
      },
      {
        id: "2010305005",
        pregunta: "¿Cuál es una ventaja clave del estándar M.2 sobre SATA para el almacenamiento?",
        opciones: [
          "M.2 siempre ofrece velocidades más altas que SATA",
          "M.2 utiliza menos energía que SATA en todos los casos",
          "M.2 permite diferentes anchos y longitudes de módulo, siendo más flexible físicamente",
          "M.2 es compatible con todos los dispositivos que usan SATA",
        ],
        correcta: 2,
        explicacionId: "2010305004",
      },
      {
        id: "2010305006",
        pregunta: "¿Qué característica comparten USB 4.0 y Thunderbolt 4?",
        opciones: [
          "Ambos son buses paralelos",
          "Utilizan el mismo tipo de conector (USB tipo C)",
          "Tienen exactamente la misma velocidad de transferencia",
          "Solo se utilizan para dispositivos de almacenamiento",
        ],
        correcta: 1,
        explicacionId: "2010305004",
      },
      {
        id: "2010305007",
        pregunta: "¿Cuál es una característica distintiva de HyperTransport?",
        opciones: [
          "Es una tecnología exclusivamente paralela",
          "Solo se utiliza para conectar CPUs con GPUs",
          "Es una tecnología bidireccional de comunicaciones basada en paquetes",
          "Tiene una velocidad de transferencia fija de 10 GB/s",
        ],
        correcta: 2,
        explicacionId: "2010305004",
      },
    ],
    minimoParaAprobar: 5,
  },
  }
  
  